### ISSUE TITLE
Some test images use incorrect KTXorientation key name

### ISSUE THREAD

**Issue by sevmeyer** [KhronosGroup/KTX-Software#106]
I have noticed that some test images use the incorrect metadata key `KTXOrientation` (uppercase O), instead of the correct [`KTXorientation`](https://www.khronos.org/opengles/sdk/tools/KTX/file_format_spec/#keys):

- cubemap_yokohama_astc_8x8_unorm.ktx
- cubemap_yokohama_bc3_unorm.ktx
- cubemap_yokohama_etc2_unorm.ktx
- metalplate-amg-rgba8.ktx
- not4_rgb888_srgb.ktx
- pattern_02_bc2.ktx
- texturearray_astc_8x8_unorm.ktx
- texturearray_bc3_unorm.ktx
- texturearray_etc2_unorm.ktx

I don't expect anything to catch on fire because of this, but it seems worthwhile to mention it.

**Comment by MarkCallow** [comment]
I noticed these when working on ktx2ktx2. It caused me to add a feature to drop such invalid metadata or optionally rewrite it during the conversion. I don't have a good way to fix these .ktx files as I don't have the original images. (I would really like to get those for the Yokohama cubemap). I will have to resort to a binary editor I suppose.

Are you up for creating a PR with the fixes?

**Comment by sevmeyer** [comment]
No problem. I found the incorrect keys while working on a simple [KTX inspection tool](https://github.com/sevmeyer/ktxjuggle), which also can be used to fix the files. The real challenge was to [review the changes in Git](https://superuser.com/questions/706042/how-can-i-diff-binary-files-in-git/1251397#1251397).

On this subject, I'm working on a repository with custom KTX test files, including files with errors. Hopefully, that will be a useful contribution to the pool of test data for KTX tools.

**Comment by MarkCallow** [comment]
IIRC, I created `metalplate*` and `not4*` using PVRTexTool. Maybe it is the guilty party in the other images too, which I found on the net.

**Comment by MarkCallow** [comment]
I reported this to Imagination:

https://forums.imgtec.com/t/pvrtextool-setting-incorrect-ktx-metadata/3024

**Comment by jherico** [comment]
@MarkCallow The original yokohama images are these I believe: 
 http://www.humus.name/Textures/Yokohama3.zip  

They're JPG, but they appear to be higher quality than the KTX existing compressed versions (i.e. no terrible banding in the sky)

**Comment by jherico** [comment]
Here's the ktx version:  https://s3.amazonaws.com/Oculus/cubemap_yokohama_rgba32.zip

**Comment by jherico** [comment]
oops... looks like I accidentally found the culprit for the original bug....  my cubemap was created using PVRTexTool, and it appears to have put the incorrect `KTXOrientation` name in.  I've posted in their forum about the issue here:  https://forums.imgtec.com/t/incorrect-invalid-ktx-key-value-data/3047

**Comment by MarkCallow** [comment]
Thanks for the pointer to the Yokohama cubemaps. If I have time next week I'll try to create a Basis compressed .ktx2. I'd like to make a new .ktx files of the ETC2, ASTC & BC3 versions as well.

As I noted in an earlier comment, I posted in the imgtec forum as well. There has been no response.

**Comment by jherico** [comment]
Whoops... should have read the whole thread I guess.

**Comment by MarkCallow** [comment]
No worry. The extra post in the forum will show multiple people are interested in a fix.
