### ISSUE TITLE
One byte leak

### ISSUE THREAD

**Issue by KOMMYHAP** [KhronosGroup/KTX-Software#113]
Hi!
I found a small memory leak generated by function ktxHashList_Serialize.
If bytesOfKeyValueData equals zero and malloc is called with zero bytes, we'll have a valid pointer of allocated memory but we won't deallocate it later.
Leak is actual on Windows only.
Related links: http://c-faq.com/ansi/malloc0.html

**Comment by MarkCallow** [comment]
Ping!
