### ISSUE TITLE
How to open not compressed .ktx textures in a notepad?

### ISSUE THREAD

**Issue by BrodaJarek** [KhronosGroup/KTX-Software#121]
I have got a texture and I'd like to see what is exactly inside it. When I open it using `Visual Studio Code` it shows information: `The file is not displayed in the editor because it is either binary or uses an unsupoported text encoding` , though. Same with a wordpress, notepad.

How can I do it?

**Comment by MarkCallow** [comment]
KTX files are binary so no text editor (i.e. notepad or wordpress) would be able to open them. I am not familiar with Visual Studio Code. It probably needs some kind of plug-in understand a file type. From your description, it seems there is one but it does not display the images.

On Windows I know of the following tools for displaying and editing .ktx files:

- [PicoPixel](http://pixelandpolygon.com/picopixel-download) (Viewer)
- [PVRTexTool](https://community.imgtec.com/developers/powervr/tools/pvrtextool/) (Editor)
- [Mali Texture Compression Tool](https://developer.arm.com/tools-and-software/graphics-and-gaming/mali-texture-compression-tool) (Editor)
- [Adreno texture tool](https://developer.qualcomm.com/software/adreno-gpu-sdk/tools) (I've always found it hard to find this tool within the Adreno SDK and so have rarely used it.)
