### ISSUE TITLE
how to create a CPVRTexture from the buffer of a ktx file

### ISSUE THREAD

**Issue by nieshaoju** [KhronosGroup/KTX-Software#122]
hi, I want to create a CPVRTexture from the buffer of a ktxfile but not the filepath.
like this 
`CPVRTexture* cp = new CPVRTexture(the Buffer of ktxfile);`

**Comment by MarkCallow** [comment]
What language/platform are you using?

If PVRTexture refers to a PowerVR texture you will need to ensure that is what is contained in the KTX file. In libktx, you can create a ktxTexture object from a buffer of a KTX file with `ktxTexture_CreateFromMemory`. How you would convert that to a CPVRTexture I have no idea. Sorry. But once you've created the ktxTexture you can upload it to OpenGL or Vulkan without needing any other intermediate object.

**Comment by Naked-Hidden** [comment]
Hi,Am using c++ in windows 10.
I found there’s a method named fromKtx that can reading a ktx file by stream ，but i have not tried it yet.am gonna try it tomorrow.
  Thank you very much.
   2019.09.26 21:59 nsj

On Sep 26, 2019, at 18:01, Mark Callow <notifications@github.com> wrote:

﻿

What language/platform are you using?

If PVRTexture refers to a PowerVR texture you will need to ensure that is what is contained in the KTX file. In libktx, you can create a ktxTexture object from a buffer of a KTX file with ktxTexture_CreateFromMemory. How you would convert that to a CPVRTexture I have no idea. Sorry. But once you've created the ktxTexture you can upload it to OpenGL or Vulkan without needing any other intermediate object.

**Comment by MarkCallow** [comment]
> I found there’s a method named fromKtx

What package is that in? Is it in some library in Visual C++? I searched for it but didn't find anything.

**Comment by Naked-Hidden** [comment]
the lib and dll is in **_PowerVR_Graphics\PowerVR_Tools\PVRTexTool\Library\Windows_x86_64_**
named **PVRTexLib**
here is my code:
`CPVRTexture* cp = new CPVRTexture();`
`cp->fromKTX(/*the stream of the ktx file*/);`

**Comment by MarkCallow** [comment]
Thank you for answering your own question. Please note that PVRTexTool creates `.ktx` files with an incorrect `KTXOrientation` (instead of `KTXorientation`) metadata item. This will likely be ignored by most readers/loaders.

Closing now.
