### ISSUE TITLE
[ktx2] Basis DFD validation is inconsistent with the spec

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/KTX-Software#145]
This probably is just the old behavior (before https://github.com/KhronosGroup/KTX-Specification/pull/103), but the validator currently assumes that BasisU files need to have UNSPECIFIED color model and no sample information, whereas the spec mandates RGBSDA and valid sample information.

**Comment by MarkCallow** [comment]
Yes it is old behavior. The files currently produced by libktx are also deficient in this regard. I'm working on it. A precursor was adding @atteneder's transcode tests, just completed by PR #142.

**Comment by MarkCallow** [comment]
This was fixed a while ago. Sorry for not connecting the fix and this issue.
