### ISSUE TITLE
Vulkan mapping for S3TC compressed formats

### ISSUE THREAD

**Issue by ajtribick** [KhronosGroup/KTX-Software#153]
It looks like these mappings are the wrong way round. As far as I am aware, DXT3 should be BC2 while DXT5 should be BC3.

https://github.com/KhronosGroup/KTX-Software/blob/1768624f33f8767aa4ad73d6e3a218847d92e489/lib/vk_format.h#L677-L678

**Comment by MarkCallow** [comment]
Yes they are. Thanks for the report. This is actually fixed in the ktx2 branch. I haven't backported it because I expect to merge ktx2 into master soon. Do you need a fix urgently?

**Comment by ajtribick** [comment]
Good to know it's fixed in ktx2, thanks for the confirmation. I personally don't need an urgent fix, so I can wait for the merge.

**Comment by MarkCallow** [comment]
This is now fixed in master as well as ktx2.
