### ISSUE TITLE
Submodule checkout Aborting on https://github.com/SaschaWillems/Vulkan.git

### ISSUE THREAD

**Issue by HerkOHerk** [KhronosGroup/KTX-Software#174]
Running Mac OS Mojave.
Successfully ran:  
`git clone --recursive https://github.com/SaschaWillems/Vulkan.git`
and
`git submodule init`
but
`git submodule update` failed part way thru with the following error:

Aborting
Unable to checkout '726d14d02c95bb21ec9e43807751b491d295dd3c' in submodule path 'external/ktx'

**Comment by MarkCallow** [comment]
There is a [commit](https://github.com/KhronosGroup/KTX-Software/commit/726d14d02c95bb21ec9e43807751b491d295dd3c) with that id in KTX-Software so I do not know why the submodule update failed nor what I can do to help fix it. You should report this to github.com/SaschaWillems/Vulkan.git. They may want to update the submodule base they are using. There have been several recent fixes to the master branch.

Is the failure repeatable?

**Comment by HerkOHerk** [comment]
Re repeatability of the failure:  I retried `git submodule update` several times, and it failed every time at the same location.

I finally deleted the entire Vulkan-clone directory and retried the clone, this time watching the output of the clone.  I noticed that “external/ktx” was successfully cloned, so I left it at that and did not run `git submodule init` and  `git submodule update` which was where the repeated failures occurred.

I’m not well-versed in Git, but the apparent success of the second, complete clone in getting “external/ktx” may have been due to my having, between the first and second clones, installed git-lfs. Perhaps not having git-lfs installed at the time of the initial clone multiple failures of `git submodule update` was part or all of the problem.

Nevertheless, there were so many other issues (missing Xcode files, etc) with building Sascha Willems Vulkan that I gave up trying.  I’ll just install Vulkan/Molten myself and see if I can run Sascha Willems’ examples outside their native environment.

Thanks for your response.

Rexford Gibbs

**Comment by MarkCallow** [comment]
The issue may indeed have been related to not having git lfs installed. For future reference, if it was not installed during an initial checkout or update you can run `git lfs checkout` to retrieve the files from LFS.

I will close this as there is nothing for me to fix.

**Comment by MarkCallow** [comment]
Whoops! Forgot to close this before.
