### ISSUE TITLE
Memory leak in ktxTexture1_constructFromStreamAndHeader and ktxTexture2_constructFromStreamAndHeader

### ISSUE THREAD

**Issue by yosoymin** [KhronosGroup/KTX-Software#188]
I've found a little memory leak in both functions `ktxTexture1_constructFromStreamAndHeader` and `ktxTexture2_constructFromStreamAndHeader`, related with the variable `pKvd`. Both functions are very similar and have the same issue.
I think the problem is that after calling to `result = ktxHashList_Deserialize(&This->kvDataHead, kvdLen, pKvd);` the pointer to `pKvd` should be freed in any case (not only in case of error) because the list `kvDataHead` is copying the data from `pKvd`.

**Comment by Qubrick** [comment]
Thank you for pointing to this issue. It also fixed the older version for me as well.
https://github.com/KhronosGroup/KTX-Software/pull/57
Line 380-381 `if (result != KTX_SUCCESS) { free(pKvd);`
Change to `free(pKvd); if (result != KTX_SUCCESS) { `
