### ISSUE TITLE
Memory leak in ktxTexture2_TranscodeBasis

### ISSUE THREAD

**Issue by yosoymin** [KhronosGroup/KTX-Software#189]
There is a global static variable called `global_codebook` that is never freed. It's only one instance for all the application life, so the leak is constant, but will be great to be able to destroy it before application terminates, so CRT debug or other memory leak profilers don't complain about that.

**Comment by MarkCallow** [comment]
I don't want to add a function that an app has to call before it terminates so I suppose catching a SIGEXIT is the answer. Not sure what the equivalent is on Windows. If you know, tell me.

That said, I've often wondered about the mania for freeing memory before an application exists as the OS is going to reclaim all memory used by the app once it exits. I think it often slows down program exit.

**Comment by yosoymin** [comment]
Maybe making `global_codebook` a non-pointer global variable it's enough and more portable.

**Comment by MarkCallow** [comment]
I am having to rework this area to incorporate the latest upstream code from Basis which has an additional transcoder. I will fix this is as part of that work. I need to see how much memory it actually uses. I expect most apps will do a bunch of transcoding up front and then no more so it might be better to have an explicit way to say "done transcoding".

**Comment by MarkCallow** [comment]
Fixed in PR #200. I made it a non-pointer global variable.
