### ISSUE TITLE
toktx layers argument needs to be required_argument

### ISSUE THREAD

**Issue by yosoymin** [KhronosGroup/KTX-Software#193]
When using toktx executable to generate a texture array using --layers command line option, the parser don't take into account the next option parameter that is the number of layers to read as input files and fails thinking that the output file argument is an input file showing an error like this:

`toktx: failed to create image from filepath.ktx. Format of input file "filepath.ktx" is unsupported.`

The problem is in `toktx.cc::processOptions()`. The argument `layers `should use `required_argument` instead of `no_argument`.

**Comment by MarkCallow** [comment]
Thanks for the report. Sorry about the error.
