### ISSUE TITLE
libktx.gl.dll is depending on glew32.dll

### ISSUE THREAD

**Issue by franchice** [KhronosGroup/KTX-Software#198]
On Windows, libktx.gl.dll seems to be dependent on glew32.dll
That is, starting an app that makes use of the libktx.gl.dll will fail if glew32.dll is not found.

This happens with the debug compiled version, which I got from master branch at version #7ef7ea9. That commit is from April 09, 2020.

**Comment by MarkCallow** [comment]
Fixed in PR #127 

By some incredible coincidence this report came in at almost the exact minute I finished work on the fix for it. The delay in posting is due to all the other work bundled up in this PR.
