### ISSUE TITLE
toktx should support more input image formats

### ISSUE THREAD

**Issue by rotoglup** [KhronosGroup/KTX-Software#21]
IMHO the input formats supported by `toktx` are too exotic to be helpful/help adoption.

Using `stb_image.h` could allow to add more input format without adding another large dependency to the project.

**Comment by msc-** [comment]
Yup. It's on the TO DO list.

**Comment by MarkCallow** [comment]
`toktx` (in the ktx2 branch) now supports PNG input. It can create .ktx and .ktx2 files. I could not use stb_image.h because it does not provide access to PNG auxiliary chunks which are needed for color correctness of the created textures.

**Comment by rotoglup** [comment]
Hello @MarkCallow, this is great :) Would you mind sharing a link to the relevant code or commit ? I'd like to learn more about the auxiliary chunks, but GitHub search did not help me on this... Thanks

**Comment by MarkCallow** [comment]
I miswrote. Sorry! They're called _ancillary_ chunks. You should be able to find the information using the proper name. I've now corrected my previous comment.

The change to load PNG ancillary chunks was made in PR #96.

PR #102 also has a change related to color correctness. Converting Netpbm input files from BT.709's OETF to sRGB's.
