### ISSUE TITLE
Need FindSDL2 module

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/KTX-Software#211]
Search for SDL2 is not working, at least on macOS. Here is FindSDL2.cmake that fixes the problem. Put it in cmake/modules. You'll have to remove the .txt extension I was forced to add in order to upload it.

[FindSDL2.cmake.txt](https://github.com/KhronosGroup/KTX-Software/files/4720207/FindSDL2.cmake.txt)

**Comment by atteneder** [comment]
Done.
I sincerly hope CMake adds this module at some point so we don't have to.

**Comment by MarkCallow** [comment]
This is in draft PR #227.
