### ISSUE TITLE
interface/js_binding needs to be built.

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/KTX-Software#214]
ktx_wrapper.cpp and transcoder_wrapper.cpp need to be built with Emscripten to produce `libktx.{js,wasm}` and `msc_basis_transcoder.{js,wasm}`.

**Comment by MarkCallow** [comment]
This list of transcoders to omit when compiling for the web is given in [common_defines](https://github.com/KhronosGroup/KTX-Software/blob/e5878c262b7634350b86e80e474f7d78ece71d3c/interface/js_binding/js_binding.gypi#L12) in [js_binding.gypi](https://github.com/KhronosGroup/KTX-Software/blob/master/interface/js_binding/js_binding.gypi)

**Comment by atteneder** [comment]
The targets were in place already, so I guess your objection is about the wrong output filenames (`ktx_js.{js,wasm}` and `msc_basis_transcoder_js.{js,wasm}` ), right?

When disabling mentioned transcoders I run into the following:

```
/Users/Shared/Projects/KTX-Software/lib/basisu/transcoder/basisu_transcoder.cpp:8928:22: error: use of undeclared identifier 'slice_desc'
                BASISU_NOTE_UNUSED(slice_desc);
                                   ^
/Users/Shared/Projects/KTX-Software/lib/basisu/transcoder/basisu_transcoder.cpp:8929:22: error: use of undeclared identifier 'header'
                BASISU_NOTE_UNUSED(header);
                                   ^
```

Any idea?

**Comment by MarkCallow** [comment]
Actually I didn't see the targets. Maybe I just missed them in the long list in the project or was confused by the wrong name.

The compile error is a problem I've introduced and it is in the PR I sent to Rich. Darn it! Those variables don't exist in the modified API I created.

This is happening because you are omitting the UASTC transcoders. I am now mystified because I see `SUPPORT_UASTC=0` in the list I pointed you at. UASTC is not a transcoder target. It is one of the 2 transcoable texture formats and it should always be included. Also my test for msc_basis_transcoder transcodes both ETC1S and UASTC format textures to whatever target it choses. I shall have to figure out what is going on. Remove SUPPORT_UASTC=0 from the list and you should be fine.

**Comment by MarkCallow** [comment]
I see what happened. The affected file is part of libktx. The list to omit that is being used is the one in libktx.gypi is [hereh](https://github.com/KhronosGroup/KTX-Software/blob/e5878c262b7634350b86e80e474f7d78ece71d3c/lib/libktx.gypi#L240). BASIS_SUPPORT_UASTC=0 whould be removed from the list of defines. UASTC should always be included.

When building the bindings: ktx_wrapper.cpp and transcoder_wrapper.cpp it is not necessary to set these defines. They are only needed when building the library.

I'm going to update master to remove them and I will also fix basisu_transcoder.cpp.

**Comment by MarkCallow** [comment]
I've updated master.

**Comment by atteneder** [comment]
Great, works now!
