### ISSUE TITLE
Rename cmake generated doxygen config files

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/KTX-Software#215]
The generated Doxygen config files have .doc extensions which given the clash with MS Word is truly awful. Currently they have the form `Doxyfile.<name>.doc`. Given there is no standard extension for these files let's stick with the naming scheme currently in use `<name>.doxy`.

**Comment by atteneder** [comment]
In CMake(3.17.2)'s Doxygen module the filename is hard-coded as `Doxyfile.${targetName}`.
I can rename the targets' from `.doc` to `.doxy` to avoid the unfortunate .doc extension.

Getting the exact desired filename is feasable by not using the pre-made `doxygen_add_docs` function and create custom commands. However, that would result in more boilerplate CMake script which I'd oppose.

**Comment by MarkCallow** [comment]
I don't calling the targets something.doxy. Keeping the .doc extension is the lesser of 2 evils. Let's leave it alone.
