### ISSUE TITLE
Break up appfwSDL

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/KTX-Software#217]
We need to break up appfwSDL into 3 libraries: the underlying appfwSDL, a GLAppSDL and a VkAppSDL libraries to avoid needing a Vulkan SDK when building {es1,es3,gl3}loadtests.

**Comment by atteneder** [comment]
FWIW: in the cmake config the GL/Vulkan specific sources are not part of the appfwSDL target, but part of gl3loadtests and vkloadtests respectively.

For Vulkan this might be good enough, but once I add the GLES targest, GLAppSDL makes sense.

**Comment by atteneder** [comment]
Added `GLAppSDL`

**Comment by MarkCallow** [comment]
> FWIW: in the cmake config the GL/Vulkan specific sources are not part of the appfwSDL target, but part of gl3loadtests and vkloadtests respectively.

I saw that, yet for some reason when I tried to build gl3loadtests it wanted Vulkan. It felt like it was still building appfwSDL as a library including both the GL and Vulkan parts but I did not investigate. It was that experience that prompted opening this issue.

**Comment by atteneder** [comment]
It's independent now.
