### ISSUE TITLE
Header files don't show up in generated project

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/KTX-Software#222]
Header files aren't visible in the files listed for targets. E.g, today I was looking for GLAppSDL.h. Some of the cpp headers actually have class implementations in them so they need to appear in the source list.

I know I reported this already. I'm opening this issue so we don't forget.

**Comment by atteneder** [comment]
I remember and I thought I fixed it...strange. Will look at it tomorrow.

**Comment by MarkCallow** [comment]
Perhaps it was fixed after the PR, that you closed, so I don't have the fix.

**Comment by atteneder** [comment]
No, I didn't add all headers. Scanning them right now.

**Comment by atteneder** [comment]
Went through it...that should be it.
I didn't add things like all gtest headers. We can add those anytime the need occurs.

**Comment by MarkCallow** [comment]
Some are still missing, e.g. VulkanAppSDL.h.

**Comment by atteneder** [comment]
I've added some more, but to ensure 100% I didn't miss any, I'd have to check it with some scripts :)
probably overdoing it then

**Comment by atteneder** [comment]
I assume it's complete now. If not => reopen
