### ISSUE TITLE
Need to quiet warnings about anonymous structs & unions

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/KTX-Software#228]
The Basis code uses anonymous structs & unions with good reason. These compile on all the compilers of interest so we should silence the warnings about them being extensions. The Gyp build has been doing this for a while.

The xcode settings for clang are

        'WARNING_CFLAGS': [
          '-Wno-nested-anon-types',
          '-Wno-gnu-anonymous-struct',
        ],

For gcc it is `-Wno-pedantic`.

Visual studio does not raise warnings.

**Comment by atteneder** [comment]
should be gone now
