### ISSUE TITLE
Vulkan libs need to be copied to the app bundles.

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/KTX-Software#229]
I'd like the vkloadtests app bundles to be complete so it is possible to pass it to someone else and have it work. This means the vulkan library and layer libraris need to be copied to the bundle along with the .json files for the icd and layers. You can look at the app bundle built by the gyp build system to see where things need to end up.

**Comment by atteneder** [comment]
They should be complete now, based on inspecting the content. How can I certify for sure if I don't have a second (non-development) machine?

**Comment by MarkCallow** [comment]
Once they're compiled to use the hardened runtime and signed you should get errors if they try to use Vulkan libs outside the bundle. One test is to copy the bundle out of the build directory to somewhere unrelated to the project and then double-click it to run it.

**Comment by MarkCallow** [comment]
This has been fixed.
