### ISSUE TITLE
CI for iOS failing

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/KTX-Software#236]
It is failing because it has no include path for the Vulkan headers.

The iOS build works on macOS because it finds the headers in /usr/local/include (though only if you have run vulkan_install.py). This is not run by CI so they're not found. The iOS compile commands for VulkanAppSDL sources have 

```
-F/Volumes/vulkansdk-macos-1.2.141.1/MoltenVK/iOS/framework
```

but that framework includes only the headers for the proprietary MoltenVK API. The compiles need to search $VULKAN_INSTALL_DIR/macOS/include.

Here's [the log](https://travis-ci.com/github/KhronosGroup/KTX-Software/jobs/347745492) from a sample broken build

**Comment by atteneder** [comment]
fixed

**Comment by MarkCallow** [comment]
Forgot to say the load tests don't need the MoltenVK specific headers so no need for the -F option.
