### ISSUE TITLE
file size estimates?

### ISSUE THREAD

**Issue by mlimper** [KhronosGroup/KTX-Software#239]
Hi everyone,

is there a chance to estimate the final size of a compressed (basis payload) image, without having to actually write it out?

Just asking because compressing takes quite a while, so it would be great if there'd be a way to get an estimate up-front in a faster way, somehow.

Thanks in advance!

**Comment by MarkCallow** [comment]
I don't know the answer. I suspect not but am making enquiries.

What would such an estimate help you decide?  It is already clear that a BasisLZ/ETC1S image will be much, much smaller than the uncompressed image and also much smaller than the ETC1 compressed image. You can easily calculate the size of after block-compression. Actual compression of the variable rate portion (BasisLZ or zstd, if using UASTC/Zstd) is dependent on the image hence I think a quick answer is unlikely.

**Comment by MarkCallow** [comment]
Yes. It is difficult and any estimate beyond the 8bpp for UASTC and 4bpp for ETC1S would be wildly inaccurate for some textures.

**Comment by mlimper** [comment]
> What would such an estimate help you decide?

Target texture resolution for example, assuming we would have a fixed filesize budget but a flexible resolution to choose.

Many thanks for your answer, and sorry for the late reply!
