### ISSUE TITLE
Add config option for read and upload only

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/KTX-Software#241]
In other words, omit the writer.

**Comment by atteneder** [comment]
Would you prefer another lib/target (like `ktx_read`) or just an option that turns the `ktx` library into a read-only one?

I lean towards extra library for follwing reasons:

- No extra configuration change (helps devs without much CMake experience)
- No need to turn off/avoid depending targets (tools,tests, apps) that need the writer => simpler CMake

We could still add an option to build just the read-only lib, but by default everything is built.

**Comment by MarkCallow** [comment]
I prefer an extra library too.

**Comment by MarkCallow** [comment]
This was implemented a long time ago.
