### ISSUE TITLE
PNG with 16-bit channels aren't supported as inputs when using supercompression

### ISSUE THREAD

**Issue by zeux** [KhronosGroup/KTX-Software#255]
I get this error when trying to compress some textures using either Basis ETC1S or UASTC; basisu executable compresses these images fine. I'm not sure how these are different, since it's only a few images from glTF-Sample-Models, notably camera_camera_BaseColor.png (from https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AntiqueCamera/glTF).

This is using the latest Windows binary build from this repository.

![image](https://user-images.githubusercontent.com/1106629/86502426-cac60180-bd57-11ea-8e97-136a92b5c23e.png)

**Comment by MarkCallow** [comment]
I am unable to reproduce this on either Windows or macOS using the beta3 release downloads nor with my latest working version. The reasons for `KTX_INVALID_OPERATION` at the point of the printf are as follows:

1. The ktxTexture is already supercompressed.
2. The ktxTexture's format is block compressed.
3. The ktxTexture's format is a packed format, e.g. RGB565.
4. The component size is > 8-bit.
5. separateRGtoRGB_A is specified but the image has only one component
6. If the Basis compressor failed.

I'm not sure how to pursue this further. Could you try building a debug version and see if you can reproduce it locally?

**Comment by zeux** [comment]
This is reproducible for me on Windows / x64 in Release (MSVC2019) using latest master. In Debug I get assertions and crashes instead, unsure if debug version ever ran cleanly on any image.

In Release, it looks like this happens because:

```
    uint32_t num_components, component_size;
    getDFDComponentInfoUnpacked(This->pDfd, &num_components, &component_size);

    if (component_size != 1)
        return KTX_INVALID_OPERATION; // Basis must have 8-bit components.
```

compoment_size is 2 here.

**Comment by zeux** [comment]
And yeah the issue is that the PNG has 16-bit channels:

```
  | Name | Value | Type
-- | -- | -- | --
◢ | state.info_png.color | {colortype=LCT_RGB (2) bitdepth=16 palette=0x0000000000000000 <NULL> ...} | LodePNGColorMode
  | colortype | LCT_RGB (2) | LodePNGColorType
  | bitdepth | 16 | unsigned int
  | ▶ palette | 0x0000000000000000 <NULL> | unsigned char *
  | palettesize | 0 | unsigned __int64
  | key_defined | 0 | unsigned int
  | key_r | 0 | unsigned int
  | key_g | 0 | unsigned int
  | key_b | 0 | unsigned int
```

**Comment by MarkCallow** [comment]
I wonder why it worked for me. It should be failing everytime. How did you get that output about the PNG file?

LodePNG must be doing some sort of truncation. I know that basisu tells it to load whatever the color type is into an RGBA8 and the the Basis compressor can only cope with 8-bit components. Do you really want hidden truncation going on?

**Comment by zeux** [comment]
> I wonder why it worked for me. It should be failing everytime. How did you get that output about the PNG file?

This is just the debugger Watch window. I didn't realize this at the time but I think I have an older copy of glTF-Sample-Models. This change:
https://github.com/KhronosGroup/glTF-Sample-Models/commit/c563e277650199daedf892b2d7d64c5acf4c9c48
migrated to 8-bit PNGs so presumably this no longer happens on latest glTF-Sample-Models, which I think explains the differences in behavior here.

**Comment by MarkCallow** [comment]
The file I've got has a bitdepth of 8. The commit message even says "migrate to 8-bit PNG". https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/AntiqueCamera/glTF/camera_camera_BaseColor.png

So what file are you actually using?

**Comment by MarkCallow** [comment]
Ah! Messages crossed in the mail.

What is your opinion about handling 16-bit components? Don't do it? Warn and do it. Just do it?

**Comment by zeux** [comment]
> What is your opinion about handling 16-bit components? Don't do it? Warn and do it. Just do it?

I feel like converting to 8-bit automatically is the best option here, probably without a warning since supercompression compromises quality at any rate (even compared to 8-bit depth inputs, ETC1S has 5-bit endpoints or thereabouts?).

**Comment by lexaknyazev** [comment]
> ETC1S has 5-bit endpoints or thereabouts?

5-bit endpoints are expanded to 8 bits (by replication) to form a base color and then 8-bit modifiers are applied to form an 8-bit final value. So for some selected inputs, ETC1S can technically preserve original 8-bit values.

**Comment by MarkCallow** [comment]
lodepng simply takes the high order byte when rescaling 16-bit to 8-bit. This is not the way recommended by the PNG specification which is

```
   output = ROUND(input * MAXOUTSAMPLE / MAXINSAMPLE)

where

   MAXINSAMPLE = (2^sampledepth)-1
   MAXOUTSAMPLE = (2^desired_sampledepth)-1
```
