### ISSUE TITLE
Clarify meaning of "toktx" CLI options

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/KTX-Software#275]
Several of the CLI options were ambiguous to me, or could be read in multiple ways. I do realize the descriptions are partly coming from the basisu tool, this just happens to be what I'm using – if you'd prefer that I propose changes on that repository first I can do so.

Example:

```
--qlevel <level>
               Basis quality level. Range is 1 - 255.  Lower gives better
               compression/lower quality/faster. Higher gives less compression
               /higher quality/slower. Values of --max_endpoints and
               --max-selectors computed from this override any explicitly set
               values. Default is 128, if either of --max_endpoints or
               --max_selectors is unset, otherwise those settings rule.
```

From the 2nd to last sentence I would have assumed `--qlevel` has precedence. From the last, I would have assumed the opposite. 

I'm also unsure about the "faster" / "slower" language — does this refer to encoding speed? Faster transmission because of better compression? Faster performance on the GPU? Intuitively I expect it's the first, but not all readers will know this. For this, and other options, it would be helpful to say "encoding speed" explicitly if that is meant. Same issue in both `--uastc [<level>]` and `--uastc_rdo_d`.

Also, does `--qlevel` do anything _other than_ determine the values of `--max_selectors` and `--max_endpoints`? I.e. if a user were trying to explore the full space of options, would testing different values on the range of `--max_selectors` and `--max_endpoints` be enough, or would they need to also test that in combination with different values of `--qlevel`? 

The basisu tool mentions for its `--comp_level` option, `Mostly intended for videos. Use -q first!`. That sounds important, is there a reason not to include it in the `--clevel` option here? 

Generally I'm a little overwhelmed by the options. I think I could wrap my head around it a little easier if there were documented examples showing (1) how to get maximum quality for both ETC1S and UASTC, if you don't care about file size or encoding speed, and (2) how to get minimum file size, if you don't care about quality or encoding speed. Maybe the second is meaningless, as quality can presumably get arbitrarily bad? For example, being able to determine the highest quality I can get from ETC1S would help me to know when I need to switch to UASTC. Similarly, determining the smallest size I can get from UASTC would be useful to determine whether to continue optimizing with UASTC, or switch to a lower quality format.

One more comment, a bit more subjective:

- I would remove the `--no_multithreading` option and just accept `--threads 0` or `--threads 1` to mean the same thing.

**Comment by MarkCallow** [comment]
I agree about the difficulty of wrapping one's head around this. Examples would be good. I do not have enough knowledge to create them. We will have to consult @richgel.

On the specific issues raised, I agree with removal of `--no-multithreading` and will do it. I've always taken faster/slower to refer to encoding speed but again we should consult @richgel.

-qlevel is a shorthand way of setting the `--max_{endpoints, selectors}` (in the BasisU encoder it is endpoint_clusters and selector_clusters, but these shorter option names are the same as used by basisu tool) and `--{endpoint,selector}_rdo_threshold`. To explore the full space of options you can use those 4 options. 

If `--qlevel` option is not specified AND either `--max_endpoints` or `--max_selectors` is not set, then it is given a default value of 128. If both `--max_endpoints` and `--max_selectors` are set it is not given a value. In the lower-level encoder, if `qlevel` has been set, then values for `--max_{endpoints, selectors}`  are computed from qlevel via some heuristics. Values for `--{endpoint,selector}_rdo_threshold` are also calculated when `qlevel` > 128 but *only* for a parameter not set via a command options.

The current documentation for `--qlevel` may not be crystal clear but I don't think there is any contradiction. I will try to come up with a better description for it. Please share any suggestions you have.

> That sounds important, is there a reason not to include it in the --clevel option here?

Do you mean include the statement `Mostly intended for videos. Use -q first!`? I think that may have been added to basisu tool since I first cloned the options and I hadn't noticed. However toktx doesn't support videos at present so adding it may cause confusion.

**Comment by MarkCallow** [comment]
Here's a draft rewrite. Comments please.

``` 
     <dt>--qlevel &lt;level&gt;</dt>
     <dd>Basis quality level. Range is 1 - 255.  Lower gives better
          compression/lower quality/faster. Higher gives less compression
          /higher quality/slower. This is a shorthand way to set the
          parameters set by @b --max_endpoints, @b --max-selectors,
          @b --endpoint_rdo_threshold and --selector_rdo_threshold. An
          explicit setting of @b --qlevel takes precedence over the first
          pair while the second pair always take precedence over
          @b --qlevel which anyway only sets that pair when its value
          is > 128. If @b --qlevel is not specified and either or both of
          @b --max_endpoints, @b --max_selectors is unset, it is given a
          value of 128 otherwise those parameter values are used.</dd>
```

**Comment by donmccurdy** [comment]
> Do you mean include the statement `Mostly intended for videos. Use -q first!`? ... toktx doesn't support videos at present so adding it may cause confusion.

When looking at the options available with ETC1S, my first assumption was that `--clevel` and `--qlevel` were equally important, and that both were more generally useful than other options. Perhaps I assumed that because they have more intuitive names ("compression" and "quality") whereas the others sound more advanced. I wouldn't necessarily mention videos, but if `--clevel` is really meant for video and `toktx` doesn't support that, then I think it would be valuable to indicate that `--qlevel` is a better starting point for tuning size/quality, and that `--clevel` is "advanced" or "not usually necessary".

> Here's a draft rewrite [for `--qlevel`]. Comments please.

Thanks — this is _much clearer_, but that also reveals just how complicated the interactions are. Do they need to be? One-way overrides would be easier to understand, for example:

> `@b --qlevel` automatically determines values of `@b --max_endpoints`, `@b --max-selectors`, `@b --endpoint_rdo_threshold` and `@b --selector_rdo_threshold` for the target quality level. Any of those four flags that are explicitly set will take precedence over the value computed by `@b --qlevel`.

I realize that's a change in behavior, not just wording, but would it be reasonable to simplify it that way?

**Comment by MarkCallow** [comment]
I replied earlier today but that reply seems to have disappeared....

The behavior of `qlevel` overriding both --max_endpoints and --max-selectors is dictated by the underlying encoder from Binomial's basis_universal repo. I am loathe to change this without discussing with @richgel999. The behavior of giving `qlevel` a default of 128 when not set by the user and when neither --max_endpoints nor --max-selectors is set is something done by `basisu` tool and mimicked by libktx. It seems that @richgel999 wants users to set *both* --max_endpoints and --max-selectors if they are going down that route. I suggest we discuss changes with @richgel999.

**Comment by richgel999** [comment]
Yea, if you set -max_endpoints (or -max_selectors), you are indicating that you want manual control over the codebook sizes. So the user should set both.

**Comment by donmccurdy** [comment]
Could we consider making the relationship between `--max-selectors` and `--max-endpoints` explicit, e.g. displaying a CLI error if one is set and the other is not?

> If @b --qlevel is not specified it is given a value of 128 unless both of @b --max_endpoints and @b --max_selectors are specified in which case those parameter values are used.

I'm not following this part: if `--qlevel` is not specified, but `--max-endpoints` and `--max-selectors` are, then `--qlevel` is _not_ given a default value of 128. Does that change the defaults of `--endpoint_rdo_threshold` and `--endpoint_rdo_threshold` defaults determined? Or do those defaults (1.25) independently match what the `--qlevel` default of 128 would have chosen?

> An explicit setting of @b --qlevel takes precedence over the first pair...

If I've understood correctly, this is the process that determines the actual maximum number of selectors:

![Screenshot 2020-07-27 at 4 40 48 PM](https://user-images.githubusercontent.com/1848368/88602680-181c5280-d028-11ea-8546-671ef2a9116f.jpeg)

I believe this would be more understandable if high-level flags like `--qlevel` never overrode the more specific flags. Throwing an error when only one of `--max-selectors` and `--max-endpoints` are set, but not both, would eliminate the most confusing branch of this diagram.

**Comment by MarkCallow** [comment]
> Could we consider making the relationship between --max-selectors and --max-endpoints explicit, e.g. displaying a CLI error if one is set and the other is not?

I can do that.

> I'm not following this part: if --qlevel is not specified, but --max-endpoints and --max-selectors are, then --qlevel is not given a default value of 128. Does that change the defaults of --endpoint_rdo_threshold and --endpoint_rdo_threshold defaults determined? Or do those defaults (1.25) independently match what the --qlevel default of 128 would have chosen?

Recall from earlier

> @b --qlevel which anyway only sets that pair when its value is > 128.

Pair here being the rdo_threshold parameters so in essence yes, those defaults independently match what a `--qlevel` default of 128 would have chosen.

> I believe this would be more understandable if high-level flags like --qlevel never overrode the more specific flags. 
It only overrides the more specific flags (and only 2 of them) when set by the user.

I agree it would be less confusing if we had the same behavior for both pairs of flags. I do not know if doing that would prevent some useful settings or cause other difficulties. To answer that, we have to consult @richgel999.
