### ISSUE TITLE
Emscipten builds fail on windows

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/KTX-Software#276]
https://github.com/KhronosGroup/KTX-Software/blob/10ce74544a0577da133ba8f1200ec23c1e19f5ef/cmake/version.cmake#L170-L187

The `WIN32` condition does not work when compiling on Windows with Emscripten, so CMake tries to run `./mkversion` directly and fails.

**Comment by MarkCallow** [comment]
Do you have a suggestion for how to fix this?

**Comment by DDoS** [comment]
Hi, I'm having the same issue. According to the Emscripten.cmake file CMAKE_HOST_WIN32  should be used instead.

https://github.com/emscripten-core/emscripten/blob/master/cmake/Modules/Platform/Emscripten.cmake#L34

**Comment by MarkCallow** [comment]
Fixed by PR #277.
