### ISSUE TITLE
Cleanup BC7 TranscodeTarget enums

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/KTX-Software#280]
From the `basisu_transcoder.h`:
```c
// Previously, the caller had some control over which BC7 mode the transcoder output. 
// We've simplified this due to UASTC, which supports numerous modes.
cTFBC7_M6_RGB = cTFBC7_RGBA,
cTFBC7_M5_RGBA = cTFBC7_RGBA,
cTFBC7_M6_OPAQUE_ONLY = cTFBC7_RGBA,
cTFBC7_M5 = cTFBC7_RGBA,
```

**Comment by MarkCallow** [comment]
What to you want changed?

**Comment by lexaknyazev** [comment]
> What do you want changed?

`TranscodeTarget` enum here to expose only `BC7_RGBA` instead. 
https://github.com/KhronosGroup/KTX-Software/blob/a7e37aad534100c4a1f6067ee62dbb765259db67/lib/basisu/webgl/transcoder/image_transcoder_wrapper.cpp#L650-L651

**Comment by MarkCallow** [comment]
I left those in for compatibility for users of previous transcoders. Those are the BasisU enums that the strings are mapped to so the values will be the same as cTFBC7_RGBA. Since there are very few such users, I do not object to removing them.

**Comment by lexaknyazev** [comment]
At the very least please add `TranscodeTarget.BC7_RGBA` and mark it as the preferred option.
