### ISSUE TITLE
Can't see or find output of programs being run by ctest

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/KTX-Software#281]
For example the output of unittests, texturetests and transcodetests. Without seeing the output it will be impossible to debug. You can't even tell which of their subtests failed. Same issue with the stdout/stderr of toktx when run by toktx-tests.cmake. If the output was visible one could see immediately if, e.g, toktx had a problem with an input file.

**Comment by atteneder** [comment]
Would the verbose parameter be a solution that works for you?

`ctest -C Debug --verbose`

**Comment by atteneder** [comment]
Nevermind. I'm working on a proper/better gtest integration based on the GoogleTest CMake module.

**Comment by atteneder** [comment]
After the GoogleTest CMake integration, you should see individual tests' results
