### ISSUE TITLE
Linking problem

### ISSUE THREAD

**Issue by X1l10on88** [KhronosGroup/KTX-Software#290]
Hello everyone, I'm trying to get the ktx library to work, but I'm hitting the wall in the linker. I can't find anything in the documentation regarding linking (I mean I bet I'm doing something dumb, nobody-else seems to experience this problem).

    undefined reference to ktxTexture_CreateFromNamedFile 
    undefined reference to ktxTexture_GetData 
    undefined reference to ktxTexture_GetSize 
    undefined reference to ktxTexture_GetImageOffset 
    undefined reference to ktxTexture_Destroy

**Comment by MarkCallow** [comment]
What OS are you on?

Are you trying to link your own application with libktx or are you trying to build the tools in this repo?

**Comment by X1l10on88** [comment]
Ubuntu 18.04 LTS
I'm trying to link my own application with libktx

**Comment by MarkCallow** [comment]
Do you have `-lktx` on your link command?

Did you build libktx yourself or are you using the release build's debian installer?

**Comment by X1l10on88** [comment]
I tried -lktx but the linker didn't find it, there is actually a release build debian installer?

**Comment by MarkCallow** [comment]
For `-lktx` to work you need to either build the install target or add a -L <path/to/your/ktx/build> to the link.

There is a release at https://github.com/KhronosGroup/KTX-Software/releases/tag/v4.0.0-beta3 that includes a Debian installer.

**Comment by X1l10on88** [comment]
Thanks! It fixed it
