### ISSUE TITLE
Some testimages have unsized internal formats

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/KTX-Software#30]
Some ktx files in testimages have internalformat set to an unsized value. This is invalid according to the KTX spec which points to tables of sized formats in the OpenGL spec. as possible values. An example is down_reference.ktx. rgba-reference.ktx is also possibly invalid.

Also toktx supports creating such files. That support needs to be removed.

**Comment by msc-** [comment]
See https://forums.khronos.org/showthread.php/13465-KTX-example-files-issues for the initial discussion. Let's continue it here.

**Comment by MarkCallow** [comment]
Fixed in `incoming`. toktx can no longer create such textures and attempts to load them will result in an error.
