### ISSUE TITLE
error: use of undeclared identifier 'ktxTexture2_Destroy'

### ISSUE THREAD

**Issue by holynoob86** [KhronosGroup/KTX-Software#301]
https://github.khronos.org/KTX-Software/libktx/group__reader.html#ga01ec49abe73b77f2f8db99b5d9cf46d9

The function is implemented in lib/texture2.c but there is no definition in header.
Should I use 'extern "C" void ktxTexture2_Destroy(ktxTexture2*);' in my project?

**Comment by MarkCallow** [comment]
The intent is that you should use the `ktxTexture_Destroy` macro so you call the virtual function rather than calling ktxTexture2_Destroy directly. The drawback is that you will need a cast, if your pointer is not to the `ktxTexture` base class.
