### ISSUE TITLE
win\Release-x64\zstd_static.lib invalid or corrupt file: cannot read at 0x83

### ISSUE THREAD

**Issue by LuchoLucho** [KhronosGroup/KTX-Software#302]
Hi,

I tried to build it on VS after cMAKE and I got this error on of your dependecies.

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2373	'ktxTexture2_CompressBasisEx': redefinition; different type modifiers	ktx	...KTX-Software\lib\basis_encode.cpp	384	

Can you please fix it? Let me know. Is there any way I can get a BUILD for Linux or Windows?

Regards, Luciaon.-

**Comment by MarkCallow** [comment]
Have you installed [Git LFS](https://github.com/github/git-lfs)? If not, please install it then run `git lfs checkout` in the repo root which will checkout the library binaries and all other files that are stored in Git LFS.

**Comment by MarkCallow** [comment]
Is lack of Git LFS the issue here?

**Comment by MarkCallow** [comment]
Closing as I believe lack of Git LFS caused this problem. The project's CI builds for Linux, macOS and Windows are all building successfully. If this is not your problem then add a comment here requesting it be reopened.

You can get pre-built binaries from the project's [Releases](https://github.com/KhronosGroup/KTX-Software/releases) tab but the current one is somewhat out of date dues to issues with TravisCI's deployment software.
