### ISSUE TITLE
Incorrect cmake_minimum_required 3.13 (should be 3.15)

### ISSUE THREAD

**Issue by Cry-Luca** [KhronosGroup/KTX-Software#304]
Hi, 

I tried to generate the project using Cmake 3.14 and it failed. 

This is because the support for comma separated list of compiler ids ($<CXX_COMPILER_ID:compiler_ids>) was added in version 3.15.

Cheers,

Luca

**Comment by atteneder** [comment]
Thanks for the observation!

I don't see an issue in raising the minimum required version, but I have to check if CI/CD has the proper versions at hand.
