### ISSUE TITLE
can't load glTF sample environments

### ISSUE THREAD

**Issue by seanbaxter** [KhronosGroup/KTX-Software#305]
I can't load any of the glTF sample environments. 

I'm calling:
  KTX_error_code error = ktxTexture2_CreateFromNamedFile(
    path, 
    KTX_TEXTURE_CREATE_NO_FLAGS,
    &texture
  );

and it's returning KTX_UNSUPPORTED_TEXTURE_TYPE. 

I debugged and it's breaking here:
https://github.com/KhronosGroup/KTX-Software/blob/master/lib/dfdutils/interpretdfd.c#L81

It implies it's a non-RGB texture, but I can't learn more than that because the code is so thick with macros. 

What am I doing wrong?

**Comment by MarkCallow** [comment]
What is the file you are trying to load? Please attach it to this issue or provide a URL?

**Comment by seanbaxter** [comment]
https://github.com/KhronosGroup/glTF-Sample-Environments/tree/master/helipad/charlie

**Comment by MarkCallow** [comment]
Thanks. I'm looking into it.

**Comment by MarkCallow** [comment]
The data format descriptor (DFD) is invalid so I need to investigate why ktx2check is passing the file. I'll open an issue in the glTF repo about this file.

**Comment by MarkCallow** [comment]
I opened issue https://github.com/KhronosGroup/glTF-Sample-Environments/issues/6

**Comment by MarkCallow** [comment]
I'm closing this issue as this is not a libktx problem.  I've opened issue #309 to track the problem with `ktx2check`.
