### ISSUE TITLE
ZSTD compressed textures with a packed format have a wrong ktxFormatSize::blockSizeInBits

### ISSUE THREAD

**Issue by DDoS** [KhronosGroup/KTX-Software#312]
The function ktxTexture2_calcPostInflationBlockSizeAndAlignment calls getDFDComponentInfoUnpacked even for packed formats, even though this function is documented not only work with unpacked formats. No error or warning is issued.

I ran into this issue when trying use an RG11B10F texture super-compressed using ktxsc --zcmp. If loaded on creation, the block size is reported as 3. When using ktxTexture_IterateLoadLevelFaces it's 0. The expected value is 4.

Are there any plans to make packed formats work with super-compression?

**Comment by MarkCallow** [comment]
This is a bug. Packed formats should work with supercompression. Please provide a sample texture that is not supercompressed.

**Comment by DDoS** [comment]
Hi, sorry for the wait.

Here's a sample file: https://www.dropbox.com/s/04qxvfvpvmb2v04/skybox.ktx2?dl=0
If I compress it with --zcmp this file doesn't load correctly anymore, because ktxTexture_GetRowPitch returns the wrong value.

**Comment by MarkCallow** [comment]
I'd like to include `skybox_zstd.ktx2` in this repo's Vulkan load tests. Is that okay? What is the license for the image?

How did you create it and what was the source image format?

**Comment by DDoS** [comment]
The texture originally came from https://hdrihaven.com/ and was converted to a cubemap using cmgen (a tool from https://github.com/google/filament). The license is CC0.
