### ISSUE TITLE
Please add support for MinGW / gcc under Windows

### ISSUE THREAD

**Issue by McNopper** [KhronosGroup/KTX-Software#328]
If Windows is the target platform, MSVC is assumed to be the compiler.

MinGW can be downloaded e.g. from here https://www.msys2.org/

**Comment by MarkCallow** [comment]
When you do the initial CMake configuration you should be able to choose an alternate toolset. If you have already done an initial configuration you will have to delete the build directory and start over. (One of my pet peeves with CMake is that you can't change the toolset in an already configured project and reconfigure.) If this is not working for you please explain the issues in detail.

**Comment by McNopper** [comment]
There are several problems:
Inside the C/C++ source code, MSVC is assumed to be the build system under Windows. If MinGW and gcc is used, some defines are not available and/or includes are missing.
I assume, this happens also to other build systems.

**Comment by MarkCallow** [comment]
> Inside the C/C++ source code, MSVC is assumed to be the build system under Windows. If MinGW and gcc is used, some defines are not available and/or includes are missing.

Please give some examples. There must be some errors in my use of _WIN32 and MSVC macros. The latter are intended to be MSVC specific and should not be needed when using gcc.

**Comment by MarkCallow** [comment]
The fastest way for you to get a fix in the code is for you to submit a PR. As you know I'm busy preparing for my move.

**Comment by MarkCallow** [comment]
Please submit a PR.
