### ISSUE TITLE
A couple of bugs I found in the loader.c

### ISSUE THREAD

**Issue by sasmaster** [KhronosGroup/KTX-Software#33]
1.When one loads an array texture, GL_TEXTURE_2D_ARRAY,in the loader.c it is bound to a default target which is probably GL_TEXTURE_2D.It is never bound to GL_TEXTURE_2D_ARRAY afterwards.It leads to INVALID OPERATION error when trying to rebound to GL_TEXTURE_2D_ARRAY  later.Please fix it by binding the texture only after the correct target has been set. (lines 543 -555)

2.When loading a CUBE MAP,the loader iterates over the faces,right?That's fine.But then the texture target enum that the loader returns is not GL_TEXTURE_CUBE_MAP but the last face target enum.This one also leads to a crash when used by the caller to bind a target.
I fixed it like this:

	```
if (errorCode == KTX_SUCCESS)
	{

		if (texinfo.generateMipmaps && pfGlGenerateMipmap) {
			pfGlGenerateMipmap(texinfo.glTarget);
		}
        if (iscubemap)
        {
            *pTarget = GL_TEXTURE_CUBE_MAP;
		 
        }....
```

**Comment by sasmaster** [comment]
I really wonder how nobody got on these before.Like,no one loads anything but textures 2D ? :P

**Comment by msc-** [comment]
Thank you for the bug report. Please send me a PR with the fixes.

>  really wonder how nobody got on these before.Like,no one loads anything but textures 2D ? :P
The GL loadtests only test 2D textures but it is surprising nobody else spotted these errors. I'd be happy to accept a PR with additional tests.

The tests for the new Vulkan loader (WIP over on https://github.com/msc-/KTX) include array and cube texture tests.

**Comment by sasmaster** [comment]
Sorry, I don't have the sources on github.Have no time to set all the stuff
for PR. I can drop the whole loader.c here if you wish.

**Comment by msc-** [comment]
> I can drop the whole loader.c here if you wish.

If you have a fix for #1, please drop those lines here. No need for the whole thing.

**Comment by sasmaster** [comment]
`
texnameUser = pTexture && *pTexture;
	if (texnameUser) {
		texname = *pTexture;
	} else {
		glGenTextures(1, &texname);
	}

    
    /* load as 2D texture if 1D textures are not supported */
    if (texinfo.textureDimensions == 1 &&
        ((texinfo.compressed && (pfGlCompressedTexImage1D == NULL)) ||
         (!texinfo.compressed && (pfGlTexImage1D == NULL))))
    {
        texinfo.textureDimensions = 2;
        texinfo.glTarget = GL_TEXTURE_2D;
        header.pixelHeight = 1;
    }
    
    if (header.numberOfArrayElements > 0)
    {
        if (texinfo.glTarget == GL_TEXTURE_1D)
        {
            texinfo.glTarget = GL_TEXTURE_1D_ARRAY_EXT;
        }
        else if (texinfo.glTarget == GL_TEXTURE_2D)
        {
            texinfo.glTarget = GL_TEXTURE_2D_ARRAY;
        }
        else if (texinfo.glTarget == GL_TEXTURE_CUBE_MAP)
        {
            texinfo.glTarget = GL_TEXTURE_CUBE_MAP_ARRAY;
        }
        else
        {
            /* No API for 3D arrays yet */
            return KTX_UNSUPPORTED_TEXTURE_TYPE;
        }
        texinfo.textureDimensions++;
    }
    errorTmp = glGetError();
    assert(errorTmp == 0);
    glBindTexture(texinfo.glTarget, texname);
    errorTmp = glGetError();
    assert(errorTmp == 0);

`
Before that,the glBindTexture was at the top.

**Comment by MarkCallow** [comment]
This is fixed in the new code in branch `incoming`. I'll backport the fix to master soon.

**Comment by MarkCallow** [comment]
Item #1 is now fixed in master. #2 was already fixed in master.

Both are also fixed in incoming.
