### ISSUE TITLE
[Windows Installer] Warning! PATH too long

### ISSUE THREAD

**Issue by hybridherbst** [KhronosGroup/KTX-Software#342]
Running the latest windows installer prints a weird warning message:
![image](https://user-images.githubusercontent.com/2693840/99285169-7ff4e400-2837-11eb-80cd-5ce648b591c6.png)

I'm certain PATH isn't too long, and can add things manually just fine. Maybe some internal check checks for a wrong length here?

**Comment by MarkCallow** [comment]
This is item #4 in issue #244.

@atteneder, now that a second person has reported this problem it looks even more clearly to be a CMake bug or an issue with our installer. Please investigate.

**Comment by hybridherbst** [comment]
You can manually go to your machine's environment variables and add the toktx install path to the end of the PATH variable. Seems this workaround is still required...
