### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by skanti** [KhronosGroup/KTX-Software#344]
I'm getting an

`call to 'clamp is ambigous` error in `utils/ktxapp.h` and in `utils/scapp.h` had to comment out the line 26-28 in `utils/ktxapp.h` for successful compilation.

I'm using clang 10.0 with Ubuntu 20.04

**Comment by MarkCallow** [comment]
This sounds like a warning from an older version of doxygen. Are you sure this was from the compilation? If it was from the compiler, which application(s) were you compiling when the error occurred?

There is only one definition of the clamp template and that is in `ktxapp.h`. Does the error indicate where it thinks the other definition is?

**Comment by skanti** [comment]
Pinned the error further down:

try compilation with

`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++20 -stdlib=libc++ -Wall -g")`

Since `c++17` `clamp` is in std

Thanks for the help

**Comment by skanti** [comment]
This should do it:

```
#if ((defined(_MSVC_LANG) && _MSVC_LANG < 201703L) && __cplusplus < 201703L)
template <typename T> inline T clamp(T value, T low, T high) {
  return (value < low) ? low : ((value > high) ? high : value);
}
#endif
```
