### ISSUE TITLE
WebGL warns about width/height for generated mipmaps

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/KTX-Software#345]
The ZIP attached contains six textures: 1-3 have power-of-two dimensions, and compress without issues. 4-6 are 681x400. I understand than `KHR_texture_basisu` requires multiple-of-four dimensions for hardware compatibility reasons, so I'm passing `--resize 684x400` to the `toktx` CLI for these textures. Despite that, the textures don't render correctly in WebGL (tested three.js and BabylonJS), which prints these warnings:

> COMPRESSED_RGB_S3TC_DXT1_EXT requires that width and height are block-aligned, or, if level>0, equal to 0, 1, or 2.

I'm also using `--genmipmap`. The mipmap dimensions are as follows:

![Screen Shot 2020-11-28 at 8 02 57 PM](https://user-images.githubusercontent.com/1848368/100533039-b8d87580-31b4-11eb-9278-63fd319eca25.png)

Am I correct in understanding that WebGL requires _each level_ of the mipmaps to have multiple-of-four (or 0/1/2) dimensions? If so, is it possible to obtain that with `--genmipmap`, without requiring a more drastic resize to the next power of two?

[Archive.zip](https://github.com/KhronosGroup/KTX-Software/files/5611623/Archive.zip)

Thanks!

**Comment by MarkCallow** [comment]
> Am I correct in understanding that WebGL requires each level of the mipmaps to have multiple-of-four (or 0/1/2) dimensions?

Yes.

 If so, is it possible to obtain that with --genmipmap, without requiring a more drastic resize to the next power of two?

No, mathematically impossible.

The WebGL restriction is in the process of being removed for WebGL 2.0 contexts. See https://github.com/KhronosGroup/WebGL/issues/3117.

**Comment by donmccurdy** [comment]
I see, thank you!

**Comment by donmccurdy** [comment]
I'm still having some trouble coming up with the right choice of texture dimensions for an authoring tool using KTX-Software,  given some user-provided texture of arbitrary dimensions. Does this look correct?

![IMG_0169](https://user-images.githubusercontent.com/1848368/101304963-5c013e80-37f6-11eb-95a7-68149d4a8c0b.jpeg)

In particular — I wasn't sure what to do with 1px, 2px, and 3px dimensions in the source image. My tool accomplishes resizing by passing the `--resize` flag to `toktx`, and always includes `--genmipmap`.

**Comment by MarkCallow** [comment]
@donmccurdy your flowchart looks correct to me. A 3px image would have to be resized to 4px.
