### ISSUE TITLE
Difficulties building for 64 bit windows

### ISSUE THREAD

**Issue by Chris-R-R** [KhronosGroup/KTX-Software#347]
I ran into a couple of problems trying to build this on 64-bit windows

- Downloading the zip causes troubles when building as it includes Git LFS pointer files that do not get resolved to actual lib files when building from a zip.
- Following the build instructions gives me a 32 bit Visual Studio solution file. There is a mismatch with the 64-bit lib that gets downloaded so this doesn't work. Using the CMake gui and specifying 64-bit solves this.

Not sure if these should be seen as actual bugs or just useful information that would have saved time but this could help others trying to get this to work on Windows. Dependancies are mentioned but this could probably be made to work out of the box with minimal effort.

**Comment by MarkCallow** [comment]
We build on Windows all the time. It is part of our CI. Unfortunately CMake (either command line or GUI) defaults to Windows 32-bit. You have to specify the x64 platform when configuring. We don't support 32-bit Windows for various reasons. I'll add a note to BUILDING.md.

We've never tried downloading the zip of the sources and building that. Mea culpa. That LFS pointers don't get resolved when the zip file is created sounds like a GitHub bug. I'll contact their support.

**Comment by emackey** [comment]
I ran into this problem too.  I had to clean the repo (delete the build folder) and then add `-A x64` to the first cmake command, like this:

```
# Navigate to the root of your KTX-Software clone (replace with
# your actual path)
cd /path/to/KTX-Software

# This generates build/project files in the sub-folder `build`
cmake . -A x64 -B build

# Compile the project
cmake --build build
```

This built correctly for me on Windows 64-bit.

**Comment by MarkCallow** [comment]
@atteneder is there anything we can do besides adding a note to BUILDING.md? Does the latest CMake (3.19) default to x64 on Windows?

**Comment by atteneder** [comment]
What version of Visual Studio are you experiencing this on?

According to CMake docs, VS 2017 and older default to Win32. Newer versions default to the host's architecture.

We could override this. See:

https://cmake.org/cmake/help/latest/variable/CMAKE_VS_PLATFORM_NAME_DEFAULT.html#variable:CMAKE_VS_PLATFORM_NAME_DEFAULT

**Comment by atteneder** [comment]
Correction: it cannot be override (those are read-only variables).

So you either have to supply the proper `-A ...` parameter at configuration time (for VS 2017 or older) or use a toolchain (which is even more complicated).

We could print out a warning or even abort with an error, in case we want to discourage or flat out prevent Win32 builds.

Definitely the build instructions should reflect this.

**Comment by emackey** [comment]
Yes, VS 2017, I guess I should upgrade.

It looks like the 32-bit version doesn't link correctly, possibly due to
some dependencies being 64-bit.  There may not be a way to build it
correctly.

**Comment by Chris-R-R** [comment]
I was also using VS2017. I believe the problem when building without specifying 64 bit is that it attempts to link to a 64-bit zlib library.

**Comment by MarkCallow** [comment]
I added x64 build instructions in the referenced commit. I've also changed the GitHub project settings so actual files from Git LFS will be included in the GitHub-produced zip archives.
