### ISSUE TITLE
ktxTexture2_GLUpload doesn't exist in header file.

### ISSUE THREAD

**Issue by gwcew** [KhronosGroup/KTX-Software#352]
Hello and I have an question about using ktx.h file in my project. Because I can't do uploading texture for ktxTexture2's type. The definition ktxTexture2_GLUpload doesn't exist in ktx header file. 

So how to fix this? 

I have used your release library from release page on github.

**Comment by MarkCallow** [comment]
Use `ktxTexture_GLUpload`. This determines the texture version and does the right thing. Because it is a c API, if you have a pointer of type `ktxTexture2*` you will have to cast it to `ktxTexture`.

```
result = ktxTexture_Upload(ktxTexture(myKtxTex2), ...)`
```
