### ISSUE TITLE
ERROR: Failed to transcode: Operation not allowed in the current state.

### ISSUE THREAD

**Issue by Reon90** [KhronosGroup/KTX-Software#357]
I use libktx.js/wasm as described in basic example(https://github.khronos.org/KTX-Software/libktx_js.html) and get `ERROR: Failed to transcode: Operation not allowed in the current state.`

Could you describe what does error mean?

**Comment by MarkCallow** [comment]
From the libktx [documentation](https://github.khronos.org/KTX-Software/libktx/group__reader.html#ga90cc33928a2dae962fb94b3fa2f6575d):

KTX_INVALID_OPERATION | The texture is not supercompressed.
-- | --
KTX_INVALID_OPERATION | Supercompression global data is missing, i.e., the texture object is invalid.
KTX_INVALID_OPERATION | Image data is missing, i.e., the texture object is invalid.
KTX_INVALID_OPERATION | outputFormat is PVRTC1 but the texture does does not have power-of-two dimensions.
 
The first item should read "The texture is not in a universal format". I.e. it is not BasisLZ or UASTC. This is the most likely cause in your case.

**Comment by Reon90** [comment]
@MarkCallow Yeah, you are right. The texture was compressed with ZSTD.
Does libktx have the interface to inflate it?

**Comment by MarkCallow** [comment]
libktx automatically inflates files supercompressed with Zstd when the data is read which happens either when the file is opened, if `KTX_TEXTURE_CREATE_LOAD_IMAGE_DATA_BIT` is set, or just before transcode. That is why you see 2 in the file header but 0 in the `supercompressionScheme` field of the loaded texture.

It sounds like the texture format is not in a transcodable format. You an check this by calling `ktxTexture2_isTranscodable` (in the native API). You need to look at the `vkFormat` field in the file header and the `colorModel` in the DFD. Transcodable textures have a `vkFormat` of `VK_FORMAT_UNDEFINED` (0) and either a `colorModel` of KHR_DF_MODEL_UASTC (166) or a supercompression scheme of `KTX_SS_BASIS_LZ` (1).

**Comment by Reon90** [comment]
@MarkCallow thank you for explanation, texture file is ok, I have got successful result.

Original problem is in libktx example:
`ktexture.transcodeBasis(format, 0);
  if (ktexture.transcodeBasis(format, 0) != LIBKTX.ErrorCode.SUCCESS) {`
Make a call twice is wrong 😊

**Comment by MarkCallow** [comment]
I just pushed commit https://github.com/KhronosGroup/KTX-Software/commit/15731f5f0076bfafd296f86c7388df1509d3400d to fix the example. Thanks for pointing it out.
