### ISSUE TITLE
Failure to find Perl breaks iOS xcode project generation

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/KTX-Software#364]
When I configure and generate an Xcode project to build for iOS I get the following warnings/errors from CMake:

```
Could NOT find Perl (missing: PERL_EXECUTABLE) 
CMake Warning at cmake/mkvk.cmake:14 (message):   Perl not found -> skipping mkvk target (this is harmless; only needed when   re-generating of vulkan headers and dfdutils is required) Call Stack (most recent call first):   CMakeLists.txt:22 (include)  
Could NOT find OpenGL (missing: OPENGL_gl_LIBRARY OPENGL_INCLUDE_DIR) 
Found MoltenVK.framwork at /Users/mark/vulkansdk-macos-1.2.141.1/MoltenVK/iOS/framework/MoltenVK.framework
Configuring done
CMake Error at CMakeLists.txt:167 (add_dependencies):   The dependency target "mkvk" of target "ktx_read" does not exist. Call Stack (most recent call first):   CMakeLists.txt:387 (commom_lib_settings)  
CMake Error at CMakeLists.txt:167 (add_dependencies):   The dependency target "mkvk" of target "ktx" does not exist. Call Stack (most recent call first):   CMakeLists.txt:386 (commom_lib_settings)  
Generating done
```

I also get a pop-up error message box telling me there was an error and the projects may not have been generated correctly. Indeed they were not. No .xcodeproj file was generated. I had to manually set `PERL_EXECUTABLE` in the CMake GUI, which was not easy because it only appears when _Advanced_ is checked, in order to generate the project. I have 2 versions of Perl installed, in /usr/bin and /opt/local/bin. When configuring for macOS, CMake automatically sets `PERL_EXECUTABLE` and it picks `/usr/bin/perl`.

2 things need fixing: (1) When it exists, Perl should be found when configuring for iOS and (2) if it is not found the project should still be successfully generated as the "harmless" comment in the first warning is true.

**Comment by atteneder** [comment]
Perl is detected via CMake command `find_package(Perl)` which works on my setup (perl at `/usr/bin/perl`; CMake 3.19.3; macOS 11.1; Xcode 12.4 + CLI tools). No idea what to do about it.

The other issue is a regression I fear I introduced. Fix PR is in the making.

**Comment by MarkCallow** [comment]
Which version of CMake are you using?  I was regenerating my iOS project from scratch because the hard-wired SDK version in the existing project is no longer in Xcode. The Perl executable was not found during configuration. I am using CMake 3.19.2. On the other hand my macOS project has `PERL_EXECUTABLE` set to /usr/bin/perl and I'm pretty sure that automatically found. However the from scratch configuration for macOS may have been done some time ago with a different version of CMake.

**Comment by atteneder** [comment]
@MarkCallow my setup:
> ...perl at `/usr/bin/perl`; CMake 3.19.3; macOS 11.1; Xcode 12.4 + CLI tools

result when configuring from scratch

```bash
$ cmake -G Xcode -Bbuild-test -DCMAKE_SYSTEM_NAME=iOS -DKTX_FEATURE_LOADTEST_APPS=OFF -DKTX_FEATURE_DOC=OFF
-- Found Bash: /usr/local/bin/bash  
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Perl: /usr/bin/perl (found version "5.28.2") 
-- Configuring done
-- Generating done
-- Build files have been written to: .../KTX-Software/build-test
```

**Comment by MarkCallow** [comment]
Hmm? I had LOADTEST_APPS on and I used the CMake GUI. Other than that, it seems the same as yours. I have a Perl executable in /opt/local/bin as well as /usr/bin. But if CMake was confused by that the macOS configuration would be too.
