### ISSUE TITLE
D65 Grayscale with sRGB TRC PNG Input Transparent

### ISSUE THREAD

**Issue by arpu** [KhronosGroup/KTX-Software#384]
Hey,

have a new PNG image with small Problems
![brush_Dots_baseColor](https://user-images.githubusercontent.com/14173/112361229-755dc600-8cd3-11eb-91bd-4726d4e6887e.png)

this is how it should look:
![Bildschirmfoto von 2021-03-24 19-00-02](https://user-images.githubusercontent.com/14173/112360970-2dd73a00-8cd3-11eb-96f9-338a67ff48cb.png)

after basisu compression with toktx i get:

![Bildschirmfoto von 2021-03-24 19-00-56](https://user-images.githubusercontent.com/14173/112361070-4c3d3580-8cd3-11eb-9902-df18820dc9df.png)

maybe related to https://github.com/KhronosGroup/KTX-Software/issues/375

**Comment by MarkCallow** [comment]
What are you using to transcode this and what is the transcode target format?

If you are using `libktx` to transcode it then this does appear related to #375. If another transcoder, then likely not.

**Comment by arpu** [comment]
yes i use https://github.com/zeux/meshoptimizer with toktx (libktx)

**Comment by arpu** [comment]
Tested with df3f1406c1ebca6e2815758edca9d9b0aaf74d4e and looks good! awesome work! thx
![Bildschirmfoto von 2021-04-07 10-34-23](https://user-images.githubusercontent.com/14173/113836065-d930c600-978c-11eb-95dc-9ac7ad64a41a.png)
