### ISSUE TITLE
`toktx --version` writes version string to stderr, not stdout

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/KTX-Software#389]
Running:

```shell
toktx --version 2> error.txt 1> output.txt
```

The string `toktx v4.0.0-rc1~6` is written to `error.txt` and not to `output.txt`. Is that intended? I'm trying to implement https://github.com/donmccurdy/glTF-Transform/issues/217 and want to be sure I'm checking this correctly, and in a way that future versions will support.

Thanks!

/cc @lexaknyazev

**Comment by MarkCallow** [comment]
That's what the code is doing. Unfortunately I didn't put in a comment to explain why I chose to write the version to cerr and I can't recall why. I have no plan to change it in future versions.

**Comment by donmccurdy** [comment]
Ok, thanks! I think i've got things set up to handle stdout or stderr equivalently, so no changes needed, and it should be future-proof if output changed to stdout in the future.
