### ISSUE TITLE
Fix face bytelength calculation for PVRTC1

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/KTX-Software#390]
https://github.com/KhronosGroup/KTX-Software/blob/4e0a2cea60431ef757d7e7d93b245fc074c60e19/lib/texture2.c#L2018-L2019

From the PVRTC1 spec:
> For PVRTC 4BPP formats the imageSize is calculated as:
> `(max(width, 8) * max(height, 8) * 4 + 7) / 8`
> For PVRTC 2BPP formats the imageSize is calculated as:
> `(max(width, 16) * max(height, 8) * 2 + 7) / 8`

**Comment by MarkCallow** [comment]
Are width & height in pixels? If so, this seems a really strange calculation as it easily results in a value that is not a multiple of the block size.

**Comment by lexaknyazev** [comment]
This calculation limits the minimum payload size because any PVRTC1 texture must comprise at least two words of PVRTC1 data in each dimension.

**Comment by lexaknyazev** [comment]
Additionally, the dimensions of PVRTC1 data must always be powers-of-two, so the result is always a multiple of 8.

**Comment by MarkCallow** [comment]
Ah! yes. I was forgetting about the powers-of-two requirement.

**Comment by MarkCallow** [comment]
I guess I shouldn't have put "issue" between Fixes and the number since the auto close failed.
