### ISSUE TITLE
Update VS 2019 support info

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/KTX-Software#393]
The warning in the readme mentions VS 2019 v16.5 & v16.6. Those minor version updates are no longer supported as shown on the official chart:
![servicing-baseline-2019](https://docs.microsoft.com/en-us/visualstudio/releases/2019/media/16.9/servicing-baseline-2019-16.9.png)

**Comment by MarkCallow** [comment]
Yes, the latest version of VS 2019 works again and I've reenabled VS2019 in CI. Please file a PR to update README.md.
