### ISSUE TITLE
Certain PNG images are appearing black after converting to ktx2

### ISSUE THREAD

**Issue by praveensj91** [KhronosGroup/KTX-Software#400]
I faced an issue when trying to convert png image with the alpha channel into ktx2 with basisu supercompression. I used the Babylon sandbox site(https://sandbox.babylonjs.com/) to test the converted files. I'm using version v4.0.0-rc1.

The following image appears completely black after conversion.
![4-tree-png-image-download-picture](https://user-images.githubusercontent.com/75242709/114924466-a604cb80-9e4b-11eb-8205-670827ded1e1.png)

But the following image looks perfectly fine after conversion.
![transparency](https://user-images.githubusercontent.com/75242709/114924652-dba9b480-9e4b-11eb-81b7-3e005ceb6aad.png)

I used the following command for converting the image to ktx2
`toktx --bcmp --genmipmap out.ktx2 4-tree-png-image-download-picture.png`

I haven't been able to understand why the individual channel values aren't being read at all.

**Comment by lexaknyazev** [comment]
The dimensions of the first image are 600x581. The important part here is that its height is not a multiple of 4. Some platforms reject such textures.

The `--resize <width>x<height>` option with appropriate values could be used to fix that, although it's always better to author textures with this restriction in mind.

**Comment by praveensj91** [comment]
Thanks for that information. It indeed worked after resizing it to the next multiple of 4. 
Now that you mentioned some platforms rejecting NPOT textures, I checked with the gltf loader I'm using for my app and it was loading even the non-resized one fine. But the online loaders couldn't. I will keep this in mind.

**Comment by lexaknyazev** [comment]
- Direct3D API requires the dimensions of the base mip level to be multiples of 4 for block-compressed formats.
- WebGL 1.0 requires power-of-two dimensions in most cases.
- PVRTC1 (one of possible transcoding targets) requires textures to have power-of-two dimensions and on Apple platforms requires them to be squares.
- Basis Universal compression operates on 4x4 blocks internally.

Therefore,
- texture dimensions should be aligned to an integer number of 4x4 blocks (i.e. 800x600 is fine);
- for better compatibility, they should be powers-of-two;
- for the best portability, they should be squares with power-of-two dimensions.

These more detailed guides on authoring and using universally-compressed textures may be helpful:
https://github.com/KhronosGroup/3D-Formats-Guidelines
