### ISSUE TITLE
Does libktx have an API that can save FBO data of OpenGL to KTX file?

### ISSUE THREAD

**Issue by Otis4631** [KhronosGroup/KTX-Software#401]
I only find the API that load KTX file to FBO.
It would be a great help if someone could tell me. Thank you

**Comment by MarkCallow** [comment]
No it does not. You could use libktx to write such a tool. You would

1. Use the libktx API to create a new empty ktxTexture[12].
2. Read back the framebuffer contents via glReadPixels.
3. Use ktxTexture_SetImageFromMemory to add the data to the ktxTexture
4. Use ktxTexture[12]_WriteTo* to write the KTX texture to a file, memory or stdio stream.
