### ISSUE TITLE
Textures will turn "Black"  in AR mode <model-viewer> using KTX 2.0 compression METHOD 3: ETC1S

### ISSUE THREAD

**Issue by andygomez3dart** [KhronosGroup/KTX-Software#409]
Textures will turn "Black"  in AR mode <model-viewer> using KTX 2.0 compression METHOD 3: ETC1S

In my example I used the following:

Diffuse texture: JPG file,  2048x2048 pixels
Normal texture: PNG file, 1024x1024
glb size before compression : 10.9 MB
glb size after compression : 2.17 MB
<model-viewer> version : 1.6.0

Everything works great and fast in the viewport mode <model-viewer> when using a glb file with the METHOD 3: ETC1S.
The problem comes when I start the AR (augmented reality)  as

 the 3D model turns "Black".

I wonder whether there is a problem with the way I applied the textures or it's just an incompatibility between <model-viewer> & KTX 2.0 compression at the moment.

Please find attached  the screenshots below:

Any idea about what it's going on?

![VID-20210502-WA0001](https://user-images.githubusercontent.com/79045928/116808665-007f7680-ab32-11eb-82ec-9b9bc5573c17.gif)
![VID-20210502-WA0002](https://user-images.githubusercontent.com/79045928/116808668-06755780-ab32-11eb-8305-71479f479437.gif)

**Comment by MarkCallow** [comment]
What glTF player are you using? I suggest you report the problem to the player developers. I doubt this has anything to do with KTX-Software. Most likely the player is not yet set up to support the KHR_texture_basisu extension so the texture is not being transcoded for the device.

**Comment by andygomez3dart** [comment]
Hi @MarkCallow  many thanks for replying back.
I'm using the <model-viewer> project version 1.6.0 to diplay interactive 3d models on the web . 
The GLB file was exported from blender 2.92 and it works perfect in both render &  AR environment , but only before the compression with KTX-Software. 

I got in touch already with  <model-viewer> developers, let's see what they will find out. 

So far I haven't been able to open the compressed GLB file with any other software I know. 
The <model-viewer> can read it but I am just having issues within the AR environment.

Could you kindly suggest which glTF players are currently supporting the KTX-Software ?

Cheers.

**Comment by MarkCallow** [comment]
> Could you kindly suggest which glTF players are currently supporting the KTX-Software ?

Take a look at the [KTX Tools Guide](https://github.com/KhronosGroup/3D-Formats-Guidelines/blob/main/KTXTools.md). The best bet seems to be the BabylonJS sandbox right now. I don't know if it supports AR. I thought <model-viewer> supported KTX v2 with BasisU compressed files. I'll check. Are you using the latest version?

**Comment by andygomez3dart** [comment]
Many thanks @MarkCallow  I am using the latest version of KTX. I have been in touch with the `model-viewer` team and we found out it was not working cause I was using a live server (visual studio) serving on "HTTP" to preview my code. Once I published the AR definitely works!! So perfect with the compressed textures via "HTTPS".

**Comment by andygomez3dart** [comment]
Hi @MarkCallow , yes I am using the latest version of KTX.
After taking with the guys from `model-viewer` we thought the problem was cause I was serving on HTTP with visual studio. But the problem remains even after I published serving on HTTPS.... 
thanks for the link I will check it out in the meantime.

**Comment by MarkCallow** [comment]
I was asking about the `<model_viewer>` version you are using. Is that the latest. One of the people working on `<model_viewer>` says they are "tracking this as a Scene Viewer bug". I have asked where but have not yet received a reply.

I am going to close this issue as the problem you are seeing is most unlikely to be related to the KTX software as your example is working in "viewport mode."

**Comment by MarkCallow** [comment]
The Scene Viewer people have requested you provide the model so they can investigate. The request is in the thread you started on Google Groups: https://github.com/google/model-viewer/discussions/2348.
