### ISSUE TITLE
[toktx] Multiple input files don't handle conversions properly

### ISSUE THREAD

**Issue by Spirrwell** [KhronosGroup/KTX-Software#423]
Hello!

If I for example go to create a cubemap and I explicitly set the target_type to be RGBA, and my images were in RGB format, it will always fail on the second image.

https://github.com/KhronosGroup/KTX-Software/blob/master/tools/toktx/toktx.cc#L733

These "firstImage" variables here are set BEFORE the first image gets converted to the desired format. This is what subsequent images compare against around here: https://github.com/KhronosGroup/KTX-Software/blob/master/tools/toktx/toktx.cc#L1071

The subsequent images are checked AFTER they get converted and so it will always fail. I don't believe this is the intention, but I could be wrong.

I would greatly prefer if setting the target_type/oetf did not cause this to fail.

**Comment by MarkCallow** [comment]
Thanks for reporting this. You are correct that the code is wrong. The check was original added before all the image conversion options were added and its primary purpose is still to inform if the inputs are mismatched when no conversion is being performed. @Spirrwell,  or anyone else, is there any value in warning if the inputs differ even when conversions are being performed that ultimately result in the images having the same colortype, primaries and oetf? The answer will help me determine how best to fix this issue.

**Comment by Spirrwell** [comment]
I don't have enough knowledge to say whether it'd be helpful. I imagine somebody might find it useful to get some kind of summary of what conversions took place. But to "warn" a user I think implies they could be doing something wrong, which seems difficult to determine because you have no idea what they're using it for.

**Comment by tuket** [comment]
Hi,
I have submited a pull request. It works fine for my use case, but maybe I have missed something. Let me know your thoughts.
Thaks!

**Comment by MarkCallow** [comment]
If the user is specifiying `--assign_oetf` or `--assign_primaries` and the input files are have differing OETFs or primaries, it might be nice to warn the user as they may be unaware the files are different. Also when `--convert_oetf` is specified.

**Comment by tuket** [comment]
I don't know yet if the warning is useful. What kind of files can be used as input to toktx? In the code I've only seen .bmp, .png and .jpeg. Can any of these file extensions actually hold metadata about oetf?

**Comment by MarkCallow** [comment]
toktx supports npbm (.pam, .ppm & .pgm), .png and .jp{,e}g inputs. By spec. (npbm and jpeg without metadata) or by metadata we have oetf info for them. I expect to add support for additional input formats in future.

If the flags aren't set mismatched oetf  or primaries is an error. The question is whether to be silent or issue warning when `--{assign,convert}_oetf` or `--assign_primaries` is used and the input files are mismatched in oetf or primaries respectively. I'm leaning towards a warning for `--assign_*` and silence for `--convert_oetf`.

**Comment by tuket** [comment]
""" I'm leaning towards a warning for --assign_* and silence for --convert_oetf. """
That sounds reasonable to me as well.

**Comment by tuket** [comment]
I have updated my PR to handle those warning/errors.

**Comment by MarkCallow** [comment]
Fixed by PR #466.
