### ISSUE TITLE
ktxTexture2_writeToStream does not have KTXmetalPixelFormat in its list of valid metadata

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/KTX-Software#429]

**Comment by MarkCallow** [comment]
Why the "Fixes issue #429" didn't automatically close this, I don't know.

**Comment by lexaknyazev** [comment]
@MarkCallow 
You need to exactly write `KEYWORD #ISSUE-NUMBER`, where `KEYWORD` is one of: close(s|d), fix(es|ed), resolve(s|d).
