### ISSUE TITLE
Invalid git submodule inside repository

### ISSUE THREAD

**Issue by DDoS** [KhronosGroup/KTX-Software#434]
The commit https://github.com/KhronosGroup/KTX-Software/commit/db3595932b831b27351bb8fb77f69f08919eba4a copied another repository inside this one. That repository has a git submodule inside its "Source" directory. The KTX-Software repository doesn't have a URL for that submodule, so if you clone with submodules enabled it will fail. But it's not required, if you disable submodules everything else works fine.

I ran into this problem when using CMake's FetchContent_Declare, which enables submodules by default. Starting in 3.16 you can disable them using the option `GIT_SUBMODULES ""` but that 's a bit annoying considering the submodule isn't even needed in the first place. I think it would be best to inline or remove it from this other repo.

**Comment by MarkCallow** [comment]
When you say "it isn't even needed" do you mean the other repo isn't using it even though they have the submodule? I have gtest inlined in another part of the repo so I don't want to add another copy. If the other repo is using it, it will be difficult to persuade them to remove it.

I am okay with setting our CMake minimum to 3.16 and setting `GIT_SUBMODULES ""` in the CMakeLists if that will solve the problem. Please let me know.

**Comment by DDoS** [comment]
I meant that it's not required by KTX. I'm sure the original repo uses it for its testing.

As for the fix, it applies to user of KTX, who are obtaining it through FetchContent (like me). But it's more like a workaround. Removing the submodule in KTX (by inlining it for example) would fix it without requiring a user workaround.

**Comment by MarkCallow** [comment]
Fix by commit 360d10bb518d70c35f5585c8577e89468a114a2f.
