### ISSUE TITLE
load ktx file

### ISSUE THREAD

**Issue by FarawayRay** [KhronosGroup/KTX-Software#45]
if i only load ktx file and return texture id was used opengl program, how should i do?which file can used?

**Comment by MarkCallow** [comment]
I am not entirely sure what you are asking.

To load a ktx file and get id of the texture that was created use one of the ktxLoadTexture[FMN] functions, e.g.

```c
GLint texName = 0;
GLenum target;
GLboolean isMipmapped;
GLenum glerror;
GLubyte* pKvData;
GLuint  kvDataLen;
KTX_dimensions dimensions;
KTX_error_code ktxerror;

filename = "myfile.ktx";

ktxerror = ktxLoadTextureN(filename, &texName, &target,
                           &dimensions, &isMipmapped, &glerror,
                           &kvDataLen, &pKvData);
```
The texture name (id) is returned in the `texName` variable.

Alternatively you can generate the texture name yourself and assign it to `texName`. That name will be used for the texture created by `ktxLoadTexture*`.
