### ISSUE TITLE
Cannot create 3D files with toktx

### ISSUE THREAD

**Issue by pezcode** [KhronosGroup/KTX-Software#454]
Hello 👋 

I'm trying to create a 3D texture using:
```bash
toktx --t2 --depth 3 out.ktx2 1.png 2.png 3.png
```
and toktx prints the following error:
> toktx failed to create ktxTexture; KTX error: Operation not allowed in the current state.

Is there some setting or incompatibility I should know about? Creating a 2D array texture with the same input images works, so I'm assuming they are not the problem.

Edit: It might be worth mentioning that `--depth 1` does not produce this error

**Comment by MarkCallow** [comment]
Actually creating a 2D array texture didn't work either. The output file would not have been an array texture.
