### ISSUE TITLE
Documentation example uses ktxTexture_Create which doesn't exist

### ISSUE THREAD

**Issue by ShukantPal** [KhronosGroup/KTX-Software#478]
Should it be updated to use `ktxTexture1_Create`?

**Comment by MarkCallow** [comment]
Which documentation example?

**Comment by MarkCallow** [comment]
@ShukantPal please respond. I can't find any example using `ktxTexture_Create`. If I don't hear from you by Monday, Jan 31st I will close this via a PR that fixes 2 "See Also" references to the function and a bunch of error messages in the internal test suite that still use the string.

**Comment by ShukantPal** [comment]
I no longer see that example.
