### ISSUE TITLE
Java bindings

### ISSUE THREAD

**Issue by ShukantPal** [KhronosGroup/KTX-Software#479]
Hi, I wrote Java bindings for libktx for my own use. I wanted to know if you think they can live here?

**Comment by MarkCallow** [comment]
I think that would be great. Perhaps the source can live under the `interface` directory.

Does this create a dynamic library that can be loaded into a JVM? If so the build should be added to CI and a downloadble package to the released packages.

Please make a PR.

**Comment by ShukantPal** [comment]
Yes, there are two components - the C JNI bindings and the Java classes. The C JNI bindings would be a separate dynamic library (say `libktx-jni`) and the Java stuff would ship as a JAR.

Will make PR!
