### ISSUE TITLE
Loading .basis files with ktxlib

### ISSUE THREAD

**Issue by rawnsley** [KhronosGroup/KTX-Software#484]
I'm using **libktx** to load _.ktx2_ files and it is working fine, but I can't work out how to load _.basis_ files like [this one](https://github.com/KhronosGroup/KTX-Software/blob/master/tests/testimages/color_grid.basis) using the library. When I call `ktxTexture_CreateFromMemory` or `ktxTexture2_CreateFromMemory` it returns "Not a KTX file", which is true, but I can't find any other options.

In case it's relevant I'm actually compiling **libktx_read** and running on Android.

**Comment by MarkCallow** [comment]
`libktx` does not read .basis files and is not intended to. One reason is that when it comes to complex texture structures, e.g. a cube map, too much is left unspecified and up to the user. It works fine as long as the producer and consumer are the same party but not otherwise.
