### ISSUE TITLE
How to determine the correct transcode output format for a KTX2 file

### ISSUE THREAD

**Issue by rawnsley** [KhronosGroup/KTX-Software#485]
I have a GLTF with textures packed into KTX2 files using a mix of ETC1S or UASTC. When it comes to transcoding them for OpenGL on Android I have to set the desired transcode output format to be either `KTX_TTF_ETC` or `KTX_TTF_ASTC_4x4_RGBA` and it would appear to make sense to match the output formats to the input formats, but I can't determine the source format from the loaded file.

In the original BASISU library I could determine the source format directly [like this](https://github.com/BinomialLLC/basis_universal/blob/master/webgl/transcoder/basis_wrappers.cpp#L412), but the format doesn't seem to be exposed by `libktx`.

In [this example](https://github.com/KhronosGroup/KTX-Software/blob/master/tests/loadtests/glloadtests/utils/GLTextureTranscoder.hpp#L28) I can see that you simply always transcode to `KTX_TTF_ASTC_4x4_RGBA` if it is supported by the GPU, but this misses out the simpler transcode path from ETC1S to ETC format.

**Comment by MarkCallow** [comment]
The information you want is given by the colorModel field of the data format descriptor embedded in the file. You can access it by

```
#include <KHR/khr_df.h>
...
// Assuming your ktxTexture2* is called pKtexture
uint32_t* bdb = pKtexture->pDfd+1; // Make pointer to basis descriptor block.
uint32_t colorModel = KHR_DFDVAL(bdb, MODEL);

// colorModel will be either KHR_DF_MODEL_ETC1S or KHR_DF_MODEL_UASTC.
```

You will have to download khr_df.h from [here](https://github.com/KhronosGroup/KTX-Software/blob/master/other_include/KHR/khr_df.h) as the one in the Khronos data formats repository has not yet been updated with the value for `KHR_DF_MODEL_UASTC`.

The example you point at is actually part of one of the programs used for testing the loader so I wasn't concerned about the best choice of transcode target only one that would work.

I'd be happy to accept a PR to add `ktxTexture2_isETC1S` and `ktxTexture2_isUASTC` functions. If they existed then `ktxTexture2_needsTranscoding` could be rewritten as `return isETC1S(This) || isUASTC(This);`

**Comment by rawnsley** [comment]
@MarkCallow Worked first time :-) Thanks for such a quick response.
