### ISSUE TITLE
Build error on M1 mac: set_property could not find TARGET astcenc-neon-static. 

### ISSUE THREAD

**Issue by mikejurka** [KhronosGroup/KTX-Software#490]
I'm unable to build with the instructions on a M1 Macbook Air and it appears to be related to the recent NEON support.

Repro steps:
1. `git clone --recurse-submodules git@github.com:KhronosGroup/KTX-Software.git`
2. `cd KTX-Software`
3. `cmake . -B build`

I'm seeing this error:
```
CMake Error at CMakeLists.txt:693 (set_property):
  set_property could not find TARGET astcenc-neon-static.  Perhaps it has not
  yet been created.
```

**Comment by wasimabbas-arm** [comment]
@mikejurka how did you install your cmake? I can't reproduce it with my setup but my `cmake` is an `x86_64` binary.

```
$ file /usr/local/bin/cmake
/usr/local/bin/cmake: Mach-O 64-bit executable x86_64
```

And it thinks its on Intel machine even though its on M1 and I am not providing any x86_64 switches. 

```
--   AVX2 backend    -  ON
--   SSE4.1 backend  - OFF
--   SSE2 backend    - OFF
--   NEON backend    - OFF
--   NONE backend    - OFF
--   NATIVE backend  - OFF
--   Universal bin   - OFF
--   Decompressor    - OFF
--   Diagnostics     - OFF
--   Unit tests      - OFF
```

**Comment by samwalls-arm** [comment]
> it looks like `elseif(CPU_ARCHITECTURE STREQUAL armv8 OR CPU_ARCHITECTURE STREQUAL arm64)` check is failing. I don't have an M1 to hand, If you could investigate with putting some messages in that area of code, why its not taking that path.

I tried outputting `CPU_ARCHITECTURE` before the statement, and it shows `arm64` as expected. I think the error message itself might be right since it says it's trying to look for `astcenc-neon-static`, not `astcenc-none-static` (emphasis on 'neon' vs 'none').
