### ISSUE TITLE
ktxTexture2_CompressBasisEx produces KTX_INVALID_VALUE with default parameters

### ISSUE THREAD

**Issue by Leadwerks** [KhronosGroup/KTX-Software#502]
In the header files, it says CompressBasisEx() will work if you initialize the parameters with {}:
```
/**
 * @memberof ktxTexture2
 * @~English
 * @brief Structure for passing extended parameters to
 *        ktxTexture2_CompressBasisEx.
 *
 * Passing a struct initialized to 0 (e.g. " = {};") will use the default
 * values. Only those settings to be modified need be non-zero.
 */
typedef struct ktxBasisParams {
    ktx_uint32_t structSize;
```

However, this code results in a KTX_INVALID_VALUE error code:
```
//auto err = ktxTexture2_CompressBasis(texture, 128);
ktxBasisParams params = {};
auto err = ktxTexture2_CompressBasisEx(texture, &params);
if (KTX_SUCCESS != err)
{
	ktxTexture_Destroy((ktxTexture*)texture);
	return false;
}
```
If I use the CompressBasis() function it works fine (but does not allow selection of the uastc compression method). The image itself is nothing special, just a single 512x512 RGBA image. Tested with both the 4.0.0 release, as well as the current code here on Github.

**Comment by Leadwerks** [comment]
When I set the structsize member the error went away.

I'll add a fix to make the behavior conform to the docs.

**Comment by MarkCallow** [comment]
The documentation is out of date. Sorry.

The following values need to be set:

```
    ktxBasisParams params = {};
    params.structSize = sizeof(params);
    params.compressionLevel = KTX_ETC1S_DEFAULT_COMPRESSION_LEVEL;
```

`compressionLevel` has to be explicitly set because 0 is a valid compression level but, if we don't set the equivalent parameter in the underlying BasisU compressor it defaults to a value of 1. Without an explicit setting there is either no way to set a value of 0 or we can't have the same default as BasisU.

**Comment by MarkCallow** [comment]
> I'll add a fix to make the behavior conform to the docs.

No. It is the documentation that needs to be fixed.

**Comment by Leadwerks** [comment]
Perfect, cool. 😎

**Comment by MarkCallow** [comment]
I want this open to remind me to fix the documentation. I'd be happy to accept a PR to fix it.
