### ISSUE TITLE
Bug for BC6H vulkan format?

### ISSUE THREAD

**Issue by superdump** [KhronosGroup/KTX-Software#519]
I was looking through `makedfd2vk.pl` and spotted what I think is a bug in a regular expression:

https://github.com/KhronosGroup/KTX-Software/blob/db7d66b47d5468c44b41ed3714a637b2610d4fd3/lib/dfdutils/makedfd2vk.pl#L166

The `[2-7H]` can only match one character, so it could match `BC6` or `BCH` but not `BC6H`, unless I am mistaken.

**Comment by MarkCallow** [comment]
@fluppeteer, please verify.

**Comment by fluppeteer** [comment]
Oh, that does look like I was an idiot. Thank you for catching it. I suspect it was supposed to read "BC[2-7H]+".

**Comment by MarkCallow** [comment]
There isn't any `BCH` format is there? So shouldn't it read `BC[2-7]H?`?

**Comment by fluppeteer** [comment]
Wow. I was not awake. Whatever I was thinking, I'm pretty sure I meant "BC[2-7]H?".

A comment like that could easily be left from a cut and paste or from earlier development. I'll have a look.

**Comment by superdump** [comment]
From https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/VkFormat.html I think there are the following BC formats:

```
    VK_FORMAT_BC1_RGB_UNORM_BLOCK = 131,
    VK_FORMAT_BC1_RGB_SRGB_BLOCK = 132,
    VK_FORMAT_BC1_RGBA_UNORM_BLOCK = 133,
    VK_FORMAT_BC1_RGBA_SRGB_BLOCK = 134,
    VK_FORMAT_BC2_UNORM_BLOCK = 135,
    VK_FORMAT_BC2_SRGB_BLOCK = 136,
    VK_FORMAT_BC3_UNORM_BLOCK = 137,
    VK_FORMAT_BC3_SRGB_BLOCK = 138,
    VK_FORMAT_BC4_UNORM_BLOCK = 139,
    VK_FORMAT_BC4_SNORM_BLOCK = 140,
    VK_FORMAT_BC5_UNORM_BLOCK = 141,
    VK_FORMAT_BC5_SNORM_BLOCK = 142,
    VK_FORMAT_BC6H_UFLOAT_BLOCK = 143,
    VK_FORMAT_BC6H_SFLOAT_BLOCK = 144,
    VK_FORMAT_BC7_UNORM_BLOCK = 145,
    VK_FORMAT_BC7_SRGB_BLOCK = 146,
```

As such, I think perhaps `BC([1-57]|6H)` would match strictly those.

**Comment by fluppeteer** [comment]
True, and much more sensible.

**Comment by MarkCallow** [comment]
I've created https://github.com/KhronosGroup/dfdutils/pull/6. I had to use `BC(?:[1-57]|6H)` to avoid capturing. Please take a look, especially @fluppeteer. The line in `makedfd2vk` being fixed and those around it look like they were copy-pasted from `makevkswitch` and I can't see their purpose. I have change the line in `makevkswitch` to use the same RE.
