### ISSUE TITLE
Bug with vkformat srgb?

### ISSUE THREAD

**Issue by superdump** [KhronosGroup/KTX-Software#520]
https://github.com/KhronosGroup/KTX-Software/blob/db7d66b47d5468c44b41ed3714a637b2610d4fd3/lib/dfdutils/createdfd.c#L83-L88

Why does setChannelFlags set the linear flag in the case that the suffix is srgb? That's the opposite of what should happen, isn't it?

**Comment by MarkCallow** [comment]
These are the flags for the alpha channel which is always linear. This case overrides the default setting for the s_SRGB used for the other 3 channels.
