### ISSUE TITLE
 Mipmapped array textures stored incorrectly in ktx2

### ISSUE THREAD

**Issue by superdump** [KhronosGroup/KTX-Software#562]
The KTX2 specification says that the mip array is supposed to be stored from highest mip (lowest resolution) to lowest mip (highest resolution):
https://github.khronos.org/KTX-Specification/#_mip_level_array
The level indices are supposed to be stored from the lowest mip to the highest mip:
https://github.khronos.org/KTX-Specification/#_level_index
And within the data for any one mip level, the structure of the data is meant to be for each layer, for each cube face, for each z slice of blocks, for each y row of blocks, for each x block:
https://github.khronos.org/KTX-Specification/#levelImages

However, files output from `toktk` using its `--layers <number>` option, which seems to be for creating array textures (as in those using 2d array samplers where one has to specify a layer when sampling) stores all mips for the first layer, then all mips for the second, and so on. As such, one has to iterate for each layer, for each mip level, which seems wrong?

**Comment by superdump** [comment]
This also seems to be broken in the `basisu` tool: https://github.com/BinomialLLC/basis_universal/issues/296

**Comment by superdump** [comment]
I think maybe I spoke too soon. The data does seem to be laid out as mip n layer 0 ... n, mip n-1 layer 0 ... n, etc, but the GPU wants layer 0 mip 0 ... n, layer 1 mip 0 ... n, etc. So when creating the texture buffer, you have to loop over layers, then mip levels.

**Comment by MarkCallow** [comment]
As you noted, @superdump, the data *is* laid out as specified. The specification is as it is because that is the way both OpenGL and Vulkan need it. What GPU API are you using?
