### ISSUE TITLE
Transcoding to KTX_TTF_RGBA32 degrades quality

### ISSUE THREAD

**Issue by AnonN10** [KhronosGroup/KTX-Software#564]
Am I misunderstanding something or if BasisLZ/ETC1S is a lossless compression, transcoding back to RGBA32 shouldn't cause blocky artifacts? In my case calling `ktxTexture2_TranscodeBasis` with `KTX_TTF_RGBA32` as a transcode format causes texture to look similar to BC1. Before transcoding I call `ktxTexture2_CompressBasis` with quality set to 100.

**Comment by MarkCallow** [comment]
BasisLZ/ETC1S is not lossless. It is lossy ETC1S (a subset of ETC1) block compression for a GPU followed by, optionally an RDO step and, lossless LZ-style compression. This makes the file/transmission size similar to a JPEG compressed image. ETC1 is similar to BC1 hence the result you are seeing.

**Comment by AnonN10** [comment]
In case someone gets lost in the documentation just like me, resolved by using `ktxTexture2_CompressBasisEx` with UASTC compression enabled.

**Comment by MarkCallow** [comment]
While UASTC has higher quality than ETC1S, it is also not lossless. It is another block-based compression scheme.

@AnonN10 I like to improve the documentation. Please point out areas that caused you difficulties.

**Comment by AnonN10** [comment]
@MarkCallow sorry for the late response, somehow missed the notification. I think it's just the lack of a working example with the most recent API. Overview example does this:
```cpp
int quality = 100;
result = ktxTexture2_CompressBasis(texture, quality);
```
...so I did the same and didn't realize I was using old API.
