### ISSUE TITLE
Vulkan library loading doesn't work unless loading library specifies `RTLD_GLOBAL`, meaning SDL2 and Vulkan-Hpp

### ISSUE THREAD

**Issue by rHermes** [KhronosGroup/KTX-Software#568]
Hey!

Been looking at trying the library with a personal Vulkan project, using SDL2 and Vulkan-Hpp. I've gotten it to build using KTX-Software, but on runtime it fails with the error:

```
Could not load Vulkan command: vkAllocateCommandBuffers!
```

After investigating this, I found the [following code](https://github.com/KhronosGroup/KTX-Software/blob/5c292f490bb69447da33088133ea6e0b5da3ec9c/lib/vk_funcs.c#L86-L97):

```c++
#if 0
// The Vulkan spec. recommends using vkGetInstanceProcAddr over dlsym
// (or whatever). Doing so would require a backward incompatible
// change to the libktx API to provide the VkInstance. We have no
// choice but dlsym. We can't use vkGetDeviceProcAddr because libktx
// also uses none-device-level functions.
#define VK_FUNCTION(fun)                                                     \
  if ( !(ktx_##fun = (PFN_##fun)vkGetInstanceProcAddr(instance, #fun )) ) {  \
    fprintf(stderr, "Could not load Vulkan command: %s!\n", #fun);          \
    return KTX_FALSE;                                             \
  }
#else
#if defined(__GNUC__)
// This strange casting is because dlsym returns a void* thus is not
// compatible with ISO C which forbids conversion of object pointers
// to function pointers. The cast masks the conversion from the
// compiler thus no warning even though -pedantic is set. Since the
// platform supports dlsym, conversion to function pointers must
// work, despite the mandated ISO C warning.
#define VK_FUNCTION(fun)                                                       \
  if (!(*(void **)(&ktx_##fun) = LoadProcAddr(ktxVulkanModuleHandle, #fun))) { \
    fprintf(stderr, "Could not load Vulkan command: %s!\n", #fun);             \
    return KTX_FALSE;                                                          \
  }
#else
#define VK_FUNCTION(fun)                                                       \
  if ((ktx_##fun=(PFN_##fun)LoadProcAddr(ktxVulkanModuleHandle, #fun)) == 0) { \
    fprintf(stderr, "Could not load Vulkan command: %s!\n", #fun);             \
    return KTX_FALSE;                                                          \
  }
#endif
#endif
```

From the man page of `dlsym`:

> If filename is a NULL pointer, then the returned handle is for the main program. When given to dlsym(), this handle causes a search for a symbol in the main program, followed by all shared libraries loaded at program startup, and then all shared libraries loaded by dlopen() with the flag RTLD_GLOBAL. 

The problem here is that apps which do not dynamically link to vulkan, will then not find a handle, unless `dlsym` has been called with the flag `RTLD_GLOBAL`, which neither [SDL](https://github.com/libsdl-org/SDL/blob/5394238cdc93669dd5d7696f8d4460a0b85289da/src/loadso/dlopen/SDL_sysloadso.c#L50) nor [Vulkan-Hpp](https://github.com/KhronosGroup/Vulkan-Hpp/blob/75e18ca7a530e00b3f806bcaed6e480d1e2b927f/vulkan/vulkan.hpp#L10762) do.

From reading the code and the comments in it, it seems that there has been given thought to implementing a version that does use `vkGetInstanceProcAddr` for proper loading. I would be willing to have a go at trying to implement this, either through an upgrade of `ktxVulkanDeviceInfo` and it's classes to include an `instance`, or through the approach taken by `VulkanMemoryAllocator`, where during [initialization](https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/quick_start.html#quick_start_initialization), pointers are passed in for either just the `vkGetInstanceProcAddr` or through [specifying each method](https://gpuopen-librariesandsdks.github.io/VulkanMemoryAllocator/html/struct_vma_vulkan_functions.html).

In the mean time, it might be prudent to include a warning about this in the documentation.

**Comment by MarkCallow** [comment]
How can you _not_ dynamically link to Vulkan?

`vkloadtests` uses Vulkan-Hpp and SDL and it works. How does what you are doing differ?

That said, I would be happy to have a version that does use `vkGetInstanceProcAddr` Making a new constructor for `ktxVulkanDeviceInfo` that takes an `instance` seems like the simplest way but we'd have to maintain the existing constructor as well with dlsym as the fallback so we don't break things.

**Comment by rHermes** [comment]
The way to avoid dynamically linking vulkan is to load it at runtime, using platform specific methods. In my case for linux, this is `dlopen`. Both [volk](https://github.com/zeux/volk) and [SDL2](https://wiki.libsdl.org/SDL_Vulkan_LoadLibrary) operate this way. SDL will work fine if you load it dynamically, which is what the `vkloadtests` do.

I'll get started on the new constructor for `ktxVulkanDeviceInfo` and let you know about the progress!

Once again, thanks for the quick reply :grin:

**Comment by MarkCallow** [comment]
I understand why libraries such as SDL2 prefer to load libraries at run time - in fact I wrote much of the Vulkan support code in SDL2 - but why would an app prefer loading a library at run-time rather than linking?

> SDL will work fine if you load it dynamically, which is what the vkloadtests do.

I am not understanding what you are saying here. `vkloadtests` links with `libSDL2` as well as `libvulkan`.

**Comment by rHermes** [comment]
> SDL will work fine if you load it dynamically, which is what the vkloadtests do.

Sorry about this, pure mistake on my part, should have been. "SDL2 will work fine if you also dynamically link with libvulkan, which is what vkloadtests do".

As for why you would prefer run-time rather than dynamic linking, I don't see why you would prefer to dynamically link. Not dynamically linking with vulkan just offers more flexibility. It allows SDL2 to do what it does best, which is to abstract away the platform specifics of getting me a handle to `vkGetInstanceProcAddr`, and not worry about which version of vulkan that I'm linked against.

I'm no expert on dynamic linking and building of C/C++ applications, but to me, I don't see why you would want to both dynamically link against `libvulkan` and use SDL2's mechanisms for dynamic loading of vulkan. I think a more direct example of this is the popularity of https://github.com/zeux/volk. It was recently included in LunarG's SDK and for me that is an indication that it fills some sort of need.
