### ISSUE TITLE
Creating an additional option for creating texture arrays instead of deducing from layer count

### ISSUE THREAD

**Issue by toomuchvoltage** [KhronosGroup/KTX-Software#596]
Currently toktx seems to create arrayed textures only when layers is specified to be larger than one:
```
    createInfo.numLayers = options.layers;
    createInfo.isArray = options.layers > 1;
```
This causes issues when compressed textures are generated in bulk and assigned to various slots on a variable count descriptor set of `sampler2DArray`s. The issue mainly surfaces on AMD drivers (where the `.z` component of `textureSize()` ends up being undefined in the event the combined sampler is backed by a `texture2D` and not a `texture2DArray`).

I propose a separate option of `--is-array` that sets the flag inside KTX metadata to ensure that single layer texture arrays are possible (when potentially provided alongside larger/taller arrayed textures).

**Comment by MarkCallow** [comment]
Oops. `--layers` should have been used for arrays only. I wonder how many people actually use `--layers 1` when not wanting an array. In other words, is it too late to change behavior now? If so, a new option will be needed.

**Comment by toomuchvoltage** [comment]
Thank you @MarkCallow for attending to this. Well I guess at this stage we might have to do a wider community poll?

**Comment by HonestGaming** [comment]
Perfect, thank you for the update: I'll assume that to be the new behavior. Hopefully, with a new update coming soon... I can just replace my build with yours. Much appreciated!

**Comment by toomuchvoltage** [comment]
Perfect, thank you for the update: I'll assume that to be the new behavior. Hopefully, with a new update coming soon... I can just replace my build with yours. Much appreciated!

**Comment by MarkCallow** [comment]
I'm implementing this change. What behavior do you prefer when `--layers 0` is specified on the command line:
1. silently create a non-array texture?
2. warn about possible mistake in option specification and create a non-array texture?
3. exit with an error?

**Comment by HonestGaming** [comment]
Exit with an error, it was probably unintended.
