### ISSUE TITLE
Assertion failed in ktxTexture_calcImageSize

### ISSUE THREAD

**Issue by AnonN10** [KhronosGroup/KTX-Software#617]
`Assertion failed: This->isCompressed, file G:\C++\KTX-Software-master\lib\texture.c, line 575` in function `ktxTexture_calcImageSize`

Call stack:
```
basis_transcode.cpp line 679
basis_transcode.cpp line 347
```

What I'm doing is using `ktxTexture_SetImageFromMemory` to set a mipmap pyramid, then this:
```cpp
 //compress
ktxBasisParams params = {};
params.structSize = sizeof(params);
params.qualityLevel = quality;
params.uastc = KTX_TRUE;
//params.uastcFlags = KTX_PACK_UASTC_LEVEL_DEFAULT;
auto result = ktxTexture2_CompressBasisEx(ktx_texture, &params);
```
```cpp
//transcode
if(ktxTexture2_NeedsTranscoding(ktx_texture)) {
	ktx_texture_transcode_fmt_e tf;

	if(owner->physical_device_features.features.textureCompressionETC2)
		tf = KTX_TTF_ETC;
	else if(owner->physical_device_features.features.textureCompressionBC)
		tf = KTX_TTF_BC7_RGBA;
	else if(owner->physical_device_features.features.textureCompressionASTC_LDR)
		tf = KTX_TTF_ASTC_4x4_RGBA;
	else {
		tf = KTX_TTF_RGBA32;
	}
	auto result = ktxTexture2_TranscodeBasis(ktx_texture, tf, 0);
	//                   ^assertion failed here
}
```
The assertion failure happens at the last mipmap level 10 with size 1x1 of the image with resolution 1024x1024.

I'm using the latest `master` branch. Am I doing something wrong?

**Comment by MarkCallow** [comment]
Such assertions are intended to catch internal errors and that appears to be what has happened here. Two pieces of data in the ktxTexture2 struct do not agree with each other. It looks like `ktxTexture2_CompressBasisEx` is failing to set the `isCompressed` flag on the `ktxTexture2` of the newly compressed texture. This would only be an issue if you compress a texture then transcode it. If it gets written to a file after compression and then read in before transcoding the flag will get set on read. You are doing compress then transcode right?  I have to investigate why our encode/transcode test is not triggering this assert when running in debug mode.

Can you send me your program so I can use it to verify the problem and make sure the fix works?

**Comment by AnonN10** [comment]
> Can you send me your program so I can use it to verify the problem and make sure the fix works?

I can't, unfortunately. I'll try to step through `ktxTexture2_CompressBasisEx` to see why it doesn't set the flag now that I know what's the intended behaviour is.

**Comment by MarkCallow** [comment]
> I can't, unfortunately. 

That's a shame.

> I'll try to step through ktxTexture2_CompressBasisEx to see why it doesn't set the flag now that I know what the intended behaviour is.

I didn't spot any code to set it. Perhaps I missed it.

**Comment by AnonN10** [comment]
> I didn't spot any code to set it. Perhaps I missed it.

I also couldn't find any code that sets it while stepping through (I also might have missed it). I made a search over the repository and found that it used to set the flag here at the end of `ktxTexture2_CompressAstcEx` in [lib/astc_encode.cpp](https://github.com/KhronosGroup/KTX-Software/blob/a70e831eac91c953d31ef5381b4d66559316aa80/lib/astc_encode.cpp), is `ktxTexture2_CompressBasisEx` supposed to set the flag at the end or does it call some other function that's supposed to set it?

**Comment by MarkCallow** [comment]
> is ktxTexture2_CompressBasisEx supposed to set the flag at the end or does it call some other function that's supposed to set it?

Yes. Turns out the problematic call to `ktxTexture_calcImageSize` is only made when compressing to UASTC and my test was only trying BasisLZ/ETC1S. I've made it test both now.

I'll look into why the `ktxTexture2_CompressAstcEx` doc isn't making it into the published doc.
