### ISSUE TITLE
ktxTexture2_WriteToStream is not deterministic

### ISSUE THREAD

**Issue by AnonN10** [KhronosGroup/KTX-Software#619]
`ktxTexture2_WriteToStream` always returns different size, so far pinpointed to `ktxHashList_Sort` line 359 in `writer2.c`, as it modifies the texture data.
Can't implement #614 until this is fixed.
Perhaps a fix would be to add a flag to `ktxTexture2_WriteToStream` that tells the function to not alter any data in the texture, that way we could alter the state only once when estimating the size, and then do not alter anything as previous call would put everything in its place required for proper serialization that follows.

**Comment by MarkCallow** [comment]
I haven't looked at the code yet but while I can understand that sorting the metadata items may change the size due to increased or reduced padding between items I don't see why a second sort would change the size again as it would not change the order. Further investigation is needed.

I don't like the idea of a flag because that would allow people to inadvertently or intentionally avoid the sort which is required by the KTX spec.

**Comment by AnonN10** [comment]
> I don't see why a second sort would change the size again as it would not change the order. Further investigation is needed.

Understood. In this case I'll be leaving this to you, because I don't understand how your hash implementation works and it would take way too much time for me to wrap my head around it.

**Comment by MarkCallow** [comment]
> ... because I don't understand how your hash implementation works

Nor do I. It is from a third party all implemented in `uthash.h`.

Am I understanding the issue correctly, that the serialized length is different each time you call `ktxTexture2_WriteToStream` even with no changes to the ktxTexture2 struct or to the texture's data or metadata?

**Comment by AnonN10** [comment]
> Am I understanding the issue correctly, that the serialized length is different each time you call `ktxTexture2_WriteToStream` even with no changes to the ktxTexture2 struct or to the texture's data or metadata?

Correct. The issue comes *at least* from the hash sort, and once I figured it causes a problem I didn't check anything else.

**Comment by MarkCallow** [comment]
How did you figure it comes from the hash sort?

**Comment by AnonN10** [comment]
After a heap corruption, using debugger, I executed the `ktxTexture2_WriteToStream` function over and over and observed that the estimated (by the non-actually-writing-stream) size is always different, at first I thought it's because of my not-actually-writing-stream code that I added but I tenaciously stepped through it and made sure it's not the case. Then I inspected `ktxTexture2_WriteToStream` itself around all `dststr->write(...)` calls and couldn't pinpoint it at first, so I begun to look for cases where it would modify the texture in any way (as otherwise there shouldn't be any reason it wouldn't be deterministic), and first thing I saw was a call to `ktxHashList_Sort`, then I executed `ktxTexture2_WriteToStream` using debugger multiple times with a breakpoint set to `ktxHashList_Sort` to see the effect it has, and it turns out the field `valueLen` of `kvDataHead` grows every time it's called, although it appears to have always the same value just before the call to `ktxHashList_Sort`.

**Comment by MarkCallow** [comment]
I think I found the issue. It has nothing to do with the hash functions. `ktxTexture2_WriteToStream` always adds the libktx version string to the ktxWriter metadata item without checking if it is already there. So each time it is called one more instance of the version string is added increasing the length. I never expected the function to be called more than once so never had a need to check if the string was already there.

I have to think about how to check if the correct string is already there, adding or replacing it necessary.

**Comment by MarkCallow** [comment]
This is a bug that could affect any file that is read in, processed and written out again if the app doesn't rewrite the KTXwriter metadata as well as the case at hand here.

**Comment by AnonN10** [comment]
In other words, the current hash map implementation doesn't check for duplicates like what `std::map` would do?

**Comment by MarkCallow** [comment]
No it's not that. _libktx_ adds it's own version information to the KTXwriter metadata added by the calling application. It was not checking if its version info was already in KTXwriter so always adding it. The _value_ ended up with multiple instances of the _libktx_ version info. Once it has made a new KTXwriter string it deletes the existing key/value pair from the hash list and adds a new one.

**Comment by AnonN10** [comment]
Makes sense. I'll give it a go tomorrow and let you know whether there are any other things left to resolve before the #614 is ready to be made into a PR.

**Comment by AnonN10** [comment]
Yep, that seems to be fixed now.
