### ISSUE TITLE
VkQueue flags

### ISSUE THREAD

**Issue by AnonN10** [KhronosGroup/KTX-Software#627]
Please specify in the documentation which flags should a `VkQueue` passed to `ktxVulkanDeviceInfo_Construct` have.

**Comment by MarkCallow** [comment]
No flags are required. Anyway there is only one flag `VK_DEVICE_QUEUE_CREATE_PROTECTED_BIT`. It is entirely up to application if it wants to use it, provided protected memory is available. An application that does use PM will have to use `VK_IMAGE_TILING_OPTIMAL` when calling `ktxTexture_VkUploadEx`.

Is this what you want to have documented?

**Comment by AnonN10** [comment]
No, `VkQueueFlagBits` flags

**Comment by MarkCallow** [comment]
Ahh!  Okay. I plan to make the change to the documentation shown below. Please review.

I realized in investigating this that `ktxVulkanDeviceInfo` has no knowledge of the queue family index of the queue - I can't find any way to query it when I only have the `VkQueue` handle -  so there is no way that `ktxTexture_VkUploadEx` can be modified to create shared images. It looks like at some point I'll have to add some new functions. So far nobody has requested shared image support.

```
diff --git a/lib/vkloader.c b/lib/vkloader.c
index eeabf490..2940aeb9 100644
--- a/lib/vkloader.c
+++ b/lib/vkloader.c
@@ -183,6 +183,19 @@ ktxVulkanDeviceInfo_Construct(ktxVulkanDeviceInfo* This,
  * device memory properties for ease of use when allocating device memory for
  * the images.
  *
+ * If @c VK_IMAGE_TILING_OPTIMAL will be passed to ktxTexture_VkUploadEx(), the
+ * family of the @a queue parameter must support transfers. This is true if
+ * any of @c VK_QUEUE_GRAPHICS_BIT, @c VK_QUEUE_COMPUTE_BIT or
+ * @c VK_QUEUE_TRANSFER_BIT is set in the @c queueFlags property of the queue's
+ * @c VkQueueFamilyProperties. If protected memory is being used, i.e
+ * @c queueFlags has @c VK_QUEUE_PROTECTED_BIT set, then
+ * @c VK_IMAGE_TILING_OPTIMAL must be passed to ktxTexture_VkUploadEx().
+ *
+ * All VkImages and intermediate VkBuffers used in VkUploadEx() will be created
+ * with @c VK_SHARING_MODE_EXCLUSIVE set so the queue family index property
+ * of their CreateInfo structures is ignored.
+ * of their CreateInfo structures is ignored.
+ *
  * Pass a valid ktxVulkanDeviceInfo* to any Vulkan KTX image loading
  * function to provide it with the information.
  *
@@ -344,7 +357,7 @@ do {                             \
     result = This->vkFuncs.vkAllocateCommandBuffers(device, &cmdBufInfo,
                                                     &This->cmdBuffer);
     if (result != VK_SUCCESS) {
-        return KTX_OUT_OF_MEMORY; // XXX Consider an equivalent to pGlError
+        return KTX_OUT_OF_MEMORY; // TODO: Consider an equivalent to pGlError
     }
     return KTX_SUCCESS;
```

**Comment by MarkCallow** [comment]
@AnonN10 please review the proposed change today. I want to include this in the release that I want to build tomorrow at the latest.

**Comment by AnonN10** [comment]
All good I think. Regarding shared images, if I understand correctly you mean `VK_IMAGE_CREATE_MUTABLE_FORMAT_BIT` flag? It was enough for me to create a variant of `ktxTexture_VkUploadEx` which exposes flags to be able to share images between image views with compatible formats like UNORM/SRGB.
https://github.com/KhronosGroup/KTX-Software/commit/33d07be9da515746be7143e16de401d4795f6117

**Comment by MarkCallow** [comment]
> Regarding shared images,

In this case sharing means the image can be used with queues from multiple queue families which must be specified when the image is created. No sharing means the image can be used only with queues  the family of the queue used to create the image.
