### ISSUE TITLE
something wrong with the texture flipY in threejs

### ISSUE THREAD

**Issue by Frankling** [KhronosGroup/KTX-Software#630]
something wrong with the texture flipY in threejs when use tool to translate jpg to ktx2.

**Comment by MarkCallow** [comment]
> something wrong with the texture flipY in threejs

Please file a bug with threejs, not here and provide enough information so they can take action. If you think there is something wrong with `toktx`'s handling of its `--lower_left_maps_to_s0t0` option then file another bug with a clear actionable description of the problem.
