### ISSUE TITLE
[Feature Request] Convert KTX to DDS

### ISSUE THREAD

**Issue by bartlomiejduda** [KhronosGroup/KTX-Software#633]
How to convert KTX files to DDS using this software?

If it's not possible right now, can I ask to add such option in the future?
Currently there are not many working solutions for converting KTX to DDS.
The only one that was working a while ago was crunch https://github.com/BinomialLLC/crunch
but it seems it was not updated for some time and now it is not working correctly with some new textures fromats.

**Comment by MarkCallow** [comment]
Why do you want to convert KTX files to DDS files?

The current plan to is to add a D3D texture loader to libktx and to provide a path to convert DDS files to KTX files. Looking for volunteers for both thinks.

**Comment by bartlomiejduda** [comment]
@MarkCallow For game modding purposes. For me it's easier to view and edit textures when they are in DDS format (GIMP native support etc.).

**Comment by MarkCallow** [comment]
Closing this as KTX→DDS isn't going to happen in this project for a variety of reasons.

I have proposed a project in Khronos to add KTX I/O to Gimp and Blender. I can't make any promises though.
