### ISSUE TITLE
build error, MSB806

### ISSUE THREAD

**Issue by zuixiaosanlang** [KhronosGroup/KTX-Software#636]
![image](https://user-images.githubusercontent.com/20105627/193223746-9f553a10-82e0-4c73-aa1c-1e224acffc9f.png)

build failed, what is wrong?
thanks

**Comment by MarkCallow** [comment]
There is not enough information here for me to diagnose the problem. MSB806 is a generation error that means the custom build existed with a non-zero exit code. The MS docs say

"To investigate the error, check the build output or build log to see if the custom build step produced an error with information about the problem. If not, try running it separately to check for any problems or unexpected behavior."

Please check the visual studio build log and see if there is any more information.

The first two scripts that failed are perl scripts. The third one is an awk script. Maybe you don't have those tools installed.
