### ISSUE TITLE
file INSTALL cannot find "project_root/include/ktx.h" and "project_root/include/ktxvulkan.h" 

### ISSUE THREAD

**Issue by FuXiii** [KhronosGroup/KTX-Software#650]
My [open source project](https://github.com/FuXiii/Turbo) folder structure:
![image](https://user-images.githubusercontent.com/40132375/203457889-1cc8c66b-49d9-494b-a2d8-a77e02b7ac16.png)

After `build` the project and then `install` it:
```
...  
-- Up-to-date: E:/Turbo/install/bin/toktx.exe
-- Up-to-date: E:/Turbo/install/lib/ktx.lib
  CMake Error at thirdparty/KTX-Software/cmake_install.cmake:68 (file):
    file INSTALL cannot find "E:/Turbo/include/ktx.h": No error.
  Call Stack (most recent call first):
    thirdparty/cmake_install.cmake:38 (include)
    cmake_install.cmake:38 (include)
```
and then I check the `thirdparty/KTX-Software/cmake_install.cmake:68`:
```
if(CMAKE_INSTALL_COMPONENT STREQUAL "dev" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include" TYPE FILE FILES
    "E:/Turbo/include/ktx.h"
    "E:/Turbo/include/ktxvulkan.h"
    )
endif()
```
it looks like I must create `include` folder in my project root and copy `ktx.h` and `ktxvulkan.h` from `project_root/thirdparty/KTX-Software/inlcude` into it.

Why?

**Comment by FuXiii** [comment]
In `KTX-Software/CMakeLists.txt`

**Comment by MarkCallow** [comment]
Is `thirdparty/KTX-Software/` your build directory or both source and build directory? If the latter, that hasn't been tested.

> on Windows case. there have COMPONENT : dev,library

In the non-Windows case too. I do not understand your point.

LIBRARY and RUNTIME (that's the .dll and .lib) are in the library component and PUBLIC_HEADER is in the dev component. PUBLIC_HEADER is set to `${CMAKE_SOURCE_DIR}/include/ktx.h` and `${CMAKE_SOURCE_DIR}/include/ktxvulkan.h` is added if KTX_FEATURE_VULKAN is `ON`.

The install operation is done by CI every time it builds packages. In that case it is working. The issue must have something to do with the way you are configuring the project. Please post your CMake config command.

**Comment by FuXiii** [comment]
My project structure:
* All thirdparty  project put in `project_root/thirdparty/` include `KTX-Software`(use cmake `add_subdirectory(./KTX-Software)`)
* All build file is output into `project_root/build`
![image](https://user-images.githubusercontent.com/40132375/203671255-8b8a7d89-6f43-493f-9c01-e86a211b16dd.png)

after build, I try to install use cmake, then the error come out:

**Comment by M-Gjerde** [comment]
Same error. Looking for a fix for this as well
