### ISSUE TITLE
Python bindings for libktx

### ISSUE THREAD

**Issue by ShukantPal** [KhronosGroup/KTX-Software#663]
Hello there from #479. Hopefully I was good to work with before :-)

I've learned Python and wrote some Python bindings for libktx. Do you think they should be implemented here as well?

**Comment by MarkCallow** [comment]
Hi @ShukantPal, I think Python bindings would be a great addition. I have no more bandwidth. I haven't even been able make time to add your Java bindings implementation to  Maven Central. Therefore I would have to rely on you to completely take care of this. 

This means

- Writing code and tests
- If there is anything to build, ensuring it builds it CI
- Ensuring the tests run and pass in CI on all supported platforms
- Providing code in CI to deploy to whatever the usual Python distribution channel is.

If you are willing to do all this, then go for it.

I ended up spending a lot of time getting the Java bindings to build in CI on multiple platforms. I want to avoid that in this case.

**Comment by ShukantPal** [comment]
Thanks @MarkCallow. I've completed the Python bindings. Now I'm working on adding it to the build process of this repository.

Can you point me to where the workflow for releases is (where would I add the config / code to upload the bindings to PyPI - the Python package index)?

**Comment by ShukantPal** [comment]
@MarkCallow I found a way to do this − I created a "publish" workflow that you can manually trigger after a release if you want to publish to PyPI. It will fetch the latest release from this GitHub repositories and download the pyktx-related artifacts.

The only input needed from you is:
* register at https://pypi.org/account/register/ (no verification shenanigans this time :-))
* go to https://pypi.org/manage/account/#api-tokens & generate an API token
* create a secret that can be used in the workflow in GitHub called PYPI_API_TOKEN
(steps described [here](https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#saving-credentials-on-github))

Voila, then you can go to Actions page in GitHub and trigger the workflow to publish to PyPI.
