### ISSUE TITLE
Why doesn't some PNG files 32 bit with alpha channel convert to ktx2?

### ISSUE THREAD

**Issue by JunSourceX** [KhronosGroup/KTX-Software#667]
Why doesn't some PNG files 32 bit with alpha channel convert to ktx2?

**Comment by MarkCallow** [comment]
I don't know. You must provide an example png file, the command you were trying and any error messages the command output.

**Comment by JunSourceX** [comment]
![1](https://user-images.githubusercontent.com/121014113/214308917-1f24c5fa-c930-4c59-9aad-a5f3ecbedd12.png)
This image cannot be converted to ktx2.

toktx: failed to create image from C:\Users\Pro\Pictures\test\1.png. PNG file has an ICC profile chunk. These are not supported

**Comment by MarkCallow** [comment]
> PNG file has an ICC profile chunk. These are not supported

This is a known limitation. If you know or can guess the color space of the file you avoid the error by telling `toktx` the color space with the `--assign_oetf` and `--assign_primaries` options. The first only accepts `linear` or `srgb`. Pick the closest to the actual transfer function of the file. The latter only accepts `bt709` or `none`.  You can also use `srgb` as an alternative name for `bt709`. Unless you know it is bt709, use `none`.

**Comment by MarkCallow** [comment]
Closing this as we already have ICC profile support in a to do list. Note that it will be some time before we can implement it.

**Comment by JunSourceX** [comment]
> Закрытие этого, поскольку у нас уже есть поддержка профиля ICC в списке дел. Обратите внимание, что пройдет основное время, чем прежде мы сможем реализовать его.

Thanks))
