### ISSUE TITLE
KTX,KTX2 Logo ?

### ISSUE THREAD

**Issue by blackcrack** [KhronosGroup/KTX-Software#673]
Hi Peoples ,

is there a logo for KTX or KTX2 Files for making Icons ?
i be at moment at pling (search for "blacky") for making Icons for 3 different file types,
but there is no logo/image for KTX/KTX2 file's ..

i have already make a other file type/mimetype from a KG, now have i think, i make short a ask for/because ktx ..
as issue.. if you are have something "in the hindquarters" would this the best possible for get a info for integrating :)

at this, could you short make issue for a logo for your ktx-software ;)

best regards
Blacky

**Comment by MarkCallow** [comment]
Yes, we have a logo. How exactly would you use it? Can people download them for their own use or are they used by pling.com as part of the presentation of files for download?

The only search I could find on pling.com is for categories so "blacky" is not found. How can I find the other icons you've made and see how they are being used?

**Comment by blackcrack** [comment]
https://www.pling.com/p/1925937/
https://www.pling.com/p/1955362/

a Filetype/Mime Types, 
Iana : https://www.iana.org/assignments/media-types/media-types.xhtml
Digipress : https://www.digipres.org/formats/mime-types/

https://en.wikipedia.org/wiki/OpenRaster
https://www.openraster.org/baseline/baseline.html
https://github.com/openraster/ora-spec  (have taken the heart from [achadwick](https://github.com/openraster/ora-spec/commits?author=achadwick) Cup and pared with the logo where i have finally found.. so, a logo with a lil hint ;) ) 

These be mimetypes registrations for Files to have a assignation in Type, Factory and Art  
to use in different Orderingsystems like Linux Derivat, FreeBSD, Reactos as WinNT in x86 and x86_64 (with 64 enhancements because x86 works anywhere .. ;) )

As Example, for image/openraster so, as icon name image-openraster.png :  

<img src="https://user-images.githubusercontent.com/7925717/219293694-aa18672a-7ee8-47ee-bc7d-a21b60b08fab.png" width="100" height="100" />image-openraster-modern  

<img src="https://user-images.githubusercontent.com/7925717/219293726-71c36b08-a72e-424c-8e4e-c3f2235697b9.png" width="100" height="100" />image-openraster-w2k  

<img src="https://user-images.githubusercontent.com/7925717/219293760-c3a0f52a-d507-4f67-a3c8-f722089d3358.png" width="100" height="100" />image-openraster-wxp


and KG, Kronos Group ;)

The "wide" logo of Kronos Group do i have, but this is not a pretty well logo for a mimetype of for a Grafic Program.. like KTX-Software, it's a Logo for a Factory.. a Logo for a Graphic Program, need an other Logo, like you now can see.. take a look on "MS Paint NET"

<img src="https://www.gimp.org/images/frontpage/wilber-big.png"  height="100" />  Gimp  <img src="https://user-images.githubusercontent.com/7925717/219301970-945c28c6-e5ca-4b72-89b2-67fb1e836a52.png"  height="100" />image-x-xcf-modern,  

Adobe Photoshop :  
<img src="https://user-images.githubusercontent.com/7925717/219302677-191c7a8b-05f0-4a3f-8060-5f92edda2aa0.png"  height="100" />image-vnd adobe photoshop-w2k  
<img src="https://user-images.githubusercontent.com/7925717/219302703-4dcf2b17-0045-408a-8535-846ce99de283.png"  height="100" />image-vnd adobe photoshop-wxp  
<img src="https://user-images.githubusercontent.com/7925717/219302739-3beb9324-2456-42a7-a981-059626ffbe94.png"  height="100" />image-vnd.adobe.photoshop-modern  


<img src="https://www.getpaint.net/images/Logo4.png"  height="100" />  
or  
<img src="https://media.inkscape.org/static/images/inkscape-logo.svg"   width="100" height="100" />InkScape

as only couples examples

**Comment by MarkCallow** [comment]
I am still not understanding who will use these icons and under what circumstances. Is the idea that you will create the icons and then anyone can download them from pling.com (free?) and use them how they wish?

Did you create the InkScape icon?

**Comment by blackcrack** [comment]
yes, for free..  under common creation , no money

and no, i don't create the inkscape icon and i don't create the Gimp icon,
 have create the compilation between Gimp-Icon and a empty Letter to have a  Mimetype Icon .. 

you're are should create a Logo icon for the KTX-Software to have a possible for create 
a Mimetype icons ..

hmmm.. if you have no clue about Iconthemes, Mimetype Icons and Logo's , should you take a Schooling for to become a clue about graphics and visual return message..
..

best

**Comment by MarkCallow** [comment]
Khronos does not want to make their copyrighted KTX logo available for uncontrolled use. Therefore they will not allow me to make it available to you. This is not about money. They want tools and files that use it to be compliant with the specification.

**Comment by blackcrack** [comment]
So, do you not get adveriting for free and you slip in the background over the time..   
if you do nothing for the OpenSource community and have no trust in it,   
do not need the OpenSource Community Khronos....

and the OpenSource Community is huge..around the world... you should learn for thinking other..
and have more trust in the Open Source Community..

but so far, thank you for your response Sir.

in best Regards
blacky

Blackcrack
Blackysgate (de/net)
