### ISSUE TITLE
4.1.0 rc3 install error win 10, path too long unable to set paths

### ISSUE THREAD

**Issue by DarceyLloyd** [KhronosGroup/KTX-Software#675]
4.1.0 rc3 install error win 10 pro, path too long unable to set paths

I have windows pro (latest and all updates installed) and have extended path features enabled however it still fails to install with set paths selected. Error path too long unable to set paths

**Comment by MarkCallow** [comment]
See https://github.com/KhronosGroup/KTX-Software/issues/244#issuecomment-1145739070.
