### ISSUE TITLE
Wrong block size in gl_format.h

### ISSUE THREAD

**Issue by suikki** [KhronosGroup/KTX-Software#68]
On this line the blockHeight should be 5:
https://github.com/KhronosGroup/KTX-Software/blob/4a14267af78cde7d7d360fabd072f774408d2d91/lib/gl_format.h#L2092

Where is this code originally from?

**Comment by MarkCallow** [comment]
Well spotted. Thank you. The attribution is in the original copyright at the top of the file.

Can you submit a PR?

**Comment by MarkCallow** [comment]
> Where is this code originally from?

If you mean where did I get it, I think I got it directly from Johannes van Waveren. A quick search turned up only one other copy, in the read only Vulkan-Samples repo in KhronosGroup. Anyway I have added a new function to the one in this repo so a PR is needed to fix this one.

**Comment by suikki** [comment]
I created a pull request: https://github.com/KhronosGroup/KTX-Software/pull/69

> If you mean where did I get it, I think I got it directly from Johannes van Waveren. A quick search turned up only one other copy, in the read only Vulkan-Samples repo in KhronosGroup. Anyway I have added a new function to the one in this repo so a PR is needed to fix this one.

I found that copy too. And yes, I was just wondering what the origin of file was so it could be fixed too.

**Comment by MarkCallow** [comment]
After tracking down an e-mail address I have sent a message to Johannes to let him know of the error.

**Comment by MarkCallow** [comment]
Fix by PR #69.
