### ISSUE TITLE
Command line argument ordering causes errors

### ISSUE THREAD

**Issue by Chargeuk** [KhronosGroup/KTX-Software#680]
Hi,
I am having trouble with command line arguments when using toktx v4.1.0-rc3 on windows 10.

The command:
toktx --zcmp --encode uastc –-uastc_quality 4 output.ktx2 input.png

gives the error:
toktx: failed to create image from 4. Could not open input file "4". No such file or directory

It looks to me like toktx is obtaining the input file name from the value 4 which is meant to be the uastc_quality parameter.

I did try to add the uastc_quality parameter to the very end, but it looks like it is ignored as incorrect values do not create an error message. For example the following produces a file:
toktx --zcmp --encode uastc  NormalMap.ktx2 NormalMap_flipped.png –-uastc_quality A

I have similar issues when attempting to use other parameters such as –-normal_mode and --normalize.

Is there any documentation giving examples with the correct order that these parameters must be provided?
Thanks

**Comment by MarkCallow** [comment]
When the last argument before the file names has an optional argument, as `--uastc_quality` does, you need to separate the options from the file names with `--`. Another fix is to change the option order so an option with no or a required argument appears just before the file names.

This only possible "fix" for this is improved documentation but as `toktx` is going to be replaced in the very near future, we will not update the documentation. I am therefore closing this issue.
