### ISSUE TITLE
Please ship Java interface as part of Windows/ARM64 release

### ISSUE THREAD

**Issue by robnugent** [KhronosGroup/KTX-Software#703]
Hello,

The Windows/x64 binary release ships the Java interface in 4.1.0, but this seems to be missing from the Windows/ARM64 release.

Could this be added please ?

Thanks,
Rob

**Comment by MarkCallow** [comment]
We have to cross-compile the arm64 release. I have not yet had time to find out what, if anything special, we have to do to build the Java interface in this situation. If you have knowledge, please share it.

**Comment by robnugent** [comment]
Mark,

Thanks for your response.

I'm no expert on the native code, but I managed to build this on my Windows/ARM64 box using the instructions that you provide for Windows builds in general - i.e. the same process worked for me building on Windows/ARM64 as Windows/x64.

As far as I can see the only two extra deliverables provided by the Java interface are;

bin\ktx-jni.dll
lib\libktx-4.1.0.jar

The JAR file is just Java, and so should be platform-neutral. To the best of my knowledge, I'd expect that bin\ktx-jni.dll would probably just need to be built the same way as the base bin\ktx.dll which you do already ship.

That's the limit of my knowledge I'm afraid - I'm primarily a Java programmer, so not entirely in my area of expertise here...

Thanks,
Rob

**Comment by robnugent** [comment]
@MarkCallow  - many thanks for addressing this - I'll look forward to trying this out when it appears in an offical build.
Thanks again,
Rob
