### ISSUE TITLE
How to assign KHR_DF_PRIMARIES_UNSPECIFIED? (v4.3 alpha)

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/KTX-Software#725]
Hi! I'm testing out the v4.3 alpha. In previous versions I'd specify `--assign_primaries none` for non-color textures being converted, e.g. from PNG to UASTC. There doesn't appear to be any equivalent value for the `--assign-primaries` now, is that intended? I'm not sure that color space data in the source PNG is reliable, and so would like to ensure this is set correctly in the KTX2 output.

**Comment by MarkCallow** [comment]
@VaderY, please answer this an update the documentation so it is clear.

**Comment by aqnuep** [comment]
Indeed, there's no equivalent of `KHR_DF_PRIMARIES_UNSPECIFIED` as a value for `--assign-primaries`. This wasn't called out as a requirement, but I see how that could be a problem if the input file contains incorrect information about color primaries.

There are some interactions to be considered from testing perspective, but it should be easy to add a `none` option. We'll look into this.
