### ISSUE TITLE
Use of the --format flag? (v4.3 alpha)

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/KTX-Software#726]
The new `--format` flag is described in the CLI help text as:

> KTX format enum. The enum names are matching the VkFormats without the VK_FORMAT_ prefix. If the format is an ASTC formats the ASTC encoder specific options become valid, otherwise they are ignored. Required. The VK_FORMAT_ prefix is ignored if present. Case insensitive.

From this description I'm left wondering, "KTX format enum [of what?]". If I weren't specifying `--encode uastc` I might assume that the source texture will be encoded into the specified format. If I were, I might assume either (a) I need to choose specify `VK_FORMAT_UNDEFINED` (as required for UASTC *output*) or (b) some enum value that abstractly describes the structure of the input data, even if the source format (e.g. PNG) uses a very different pixel data representation.

Clarification on this flag's help description would be very helpful, particularly as it is a required flag. Thanks!

**Comment by MarkCallow** [comment]
It is the value to be use for the vkFormat field of the KTX file's header.

Good questions. @VaderY please clarify the documentation.

**Comment by VaderY** [comment]
When using with `--encode` the `--format` option specifies the format of your input files before the encoding step. When using --encode it must be one of:
R8_UNORM
R8_SRGB
R8G8_UNORM
R8G8_SRGB
R8G8B8_UNORM
R8G8B8_SRGB
R8G8B8A8_UNORM
R8G8B8A8_SRGB

The format will be used to verify and load all your input files into a texture before encoding, The `VK_FORMAT_UNDEFINED` value will be set by the encoders and should never be specified.

**Comment by MarkCallow** [comment]
This is a great explanation. Please add it to the docs.

**Comment by donmccurdy** [comment]
> When using with `--encode` the `--format` option specifies the format of your input files before the encoding step.

Thanks! One further question. Suppose I know the image is an ambient occlusion texture, and that the data I care about is in the <kbd>R</kbd> channel. I'm not sure whether the image contains other data in the <kbd>G</kbd> or <kbd>B</kbd> channels, but I'm sure those channels do not matter for my application. Could I safely choose `R8_UNORM` here, or do I need to determine the actual contents of the input file and specify that, instead?

**Comment by VaderY** [comment]
Yes you can safely use `R8_UNORM`. Unused channels from the input are discarded silently.
Using the least amount of channels necessary is nearly always the best option as encoders can generate better compression or quality if they have to compress less channels.
