### ISSUE TITLE
Unexpected texture tiling with --target_type=R (v4.2 stable)

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/KTX-Software#727]
Running the command below on the given texture...

```bash
toktx --genmipmap --uastc 4 --uastc_rdo_l 4 --zcmp 24 --assign_oetf linear --assign_primaries none --target_type R --threads 4 occlusion_test.ktx2 occlusion_test.png
```

<details>
<summary><i>occlusion_test.png</i></summary>

![occlusion_test](https://github.com/KhronosGroup/KTX-Software/assets/1848368/284b76f1-b90c-49eb-9e61-2fbbbd94813f)

</details>

... the output is a tiled repetition of the input:

| before | after |
|----|----|
| ![before](https://github.com/KhronosGroup/KTX-Software/assets/1848368/e36aee77-31ee-4f98-9f27-25dfb6e657aa) | ![after](https://github.com/KhronosGroup/KTX-Software/assets/1848368/819388a2-1888-42ac-8eee-08127e3823f6) |

I'm not fully sure what the analog of `--target_type` is in v4.3 alpha, and so I'm not sure if the bug is present in the alpha release. Thanks!

**Comment by MarkCallow** [comment]
> I'm not fully sure what the analog of --target_type is in v4.3 alpha

`--format R8_UNORM` or `--format R8_SRGB`. I think the latter format is not widely supported.
