### ISSUE TITLE
Problem with convertion files (v4.3.0-alpha3)

### ISSUE THREAD

**Issue by Yason83** [KhronosGroup/KTX-Software#733]
While performing file conversion (files attached in the [archive](https://github.com/KhronosGroup/KTX-Software/files/11992583/images.zip)), the command line
`ktx create --format R8G8B8A8_SRGB --encode basis-lz --clevel 5 --qlevel 255 baseColor_22.png baseColor_22.ktx`

Problems
1. Fails to convert the files. 
2. The error message is not displayed.

**Comment by MarkCallow** [comment]
The example command says `baseColor_22.png` but there is no such file in the zip file. I tried with `baseColor_18.png`. It worked. Here is the result:

<img width="1280" alt="Screenshot 2023-07-09 at 21 24 51" src="https://github.com/KhronosGroup/KTX-Software/assets/2244683/b1048bb4-388f-45bc-8fa3-da3fab9da4ba">

You need to provide a lot more information about the problem. What do you mean "Fails to convert the files?"

**Comment by Yason83** [comment]
I tested on Windows11 64 (v4.3.0-alpha3)
After running the script, the result is not saved
`ktx create --format R8G8B8_SRGB --encode basis-lz --clevel 5 --qlevel 255 baseColor_18.png baseColor_18.ktx2`

![48](https://github.com/KhronosGroup/KTX-Software/assets/32398829/bc2683e4-c794-48fa-9505-87993c970052)

**Comment by MarkCallow** [comment]
It appears to be a Windows-specific problem. I was previously trying on macOS/arm64. When I try on Windows/arm64 I get no output file and no errors as reported in this issue. I also get no warning messages from `create`. I didn't get any on macOS either. I'm specifying `R8G8B8A8_SRGB` format with `baseColor_18.png` as input. 

In the debugger, I'm getting an access violation exception at line 815 in image.hpp. Two questions: why the violation and why does the app silently exit. @VaderY please investigate.

**Comment by VaderY** [comment]
Successfully reproduced it. Will look into it ASAP.

**Comment by VaderY** [comment]
The issue was typo that caused miss addressing. I will add additional tests to cover these and post a PR later today with the fix.
