### ISSUE TITLE
Problem with textures non power-of-two size (v4.3.0-alpha3)

### ISSUE THREAD

**Issue by Yason83** [KhronosGroup/KTX-Software#736]
Windows11 +  v4.3.0-alpha3
`ktx create --format R8G8B8_SRGB --encode basis-lz --clevel 5 --qlevel 255 TeakVeneer_2K_albedo.jpg TeakVeneer_2K_albedo.ktx2` 
produces unpredictable effects when loading textures with dimensions that are different from a power-of-two size.
In the case of the "TeakVeneer.jpg" texture, no errors occurred, but the texture was not created.
In the case of the "TeakVeneer_512x510.jpg" texture, no errors occurred, but the texture was distorted.
[TeakVeneer_512x510.zip](https://github.com/KhronosGroup/KTX-Software/files/12009393/TeakVeneer_512x510.zip)

**Comment by Yason83** [comment]
It would be logical in both cases to either display an error indicating that the texture is not supported or correctly convert it.

**Comment by VaderY** [comment]
Related to #733.
The #735 PR will solve this issue too.
