### ISSUE TITLE
Bug: ktx_strncasecmp doesn't work with format containing VK_FORMAT_

### ISSUE THREAD

**Issue by wasimabbas-arm** [KhronosGroup/KTX-Software#740]
I think https://github.com/KhronosGroup/KTX-Software/blob/3153e94e822eae092a337a64544fc4f0b0b3e644/lib/vkformat_str.c#L604 doesn't work because AFAICT there seems to be a bug in `ktx_strncasecmp`. Have a look at https://godbolt.org/z/xnTGhPnc7. As the comments says 

`std::cout << stringToVkFormat("VK_FORMAT_ASTC_6x6_UNORM_BLOCK") << std::endl;           // Since VK_FORMAT_ASTC_6x6_UNORM_BLOCK = 165, should print 165 but prints 0`

Should print 165 but it prints 0. Further details in the next line by just calling `ktx_strncasecmp` like how `stringToVkFormat` uses it but with the specific enum value:

```
	auto str = "VK_FORMAT_ASTC_6x6_UNORM_BLOCK";

        if (ktx_strncasecmp(str, "VK_FORMAT_", sizeof("VK_FORMAT_") - 1) == 0)
		std::cout << "found it" << std::endl;
	else
		std::cout << "didn't find it" << std::endl;
```

Should print "found it" instead it prints "didn't find it".

**Comment by wasimabbas-arm** [comment]
@MarkCallow Here is the bug report about the issue I mentioned over email.

**Comment by VaderY** [comment]
Thank you for the detailed report. I will look into it
