### ISSUE TITLE
super bright HDR pixel will result in INF when converting to ktx image

### ISSUE THREAD

**Issue by jjiangweilan** [KhronosGroup/KTX-Software#756]
I download [this](https://polyhaven.com/a/rural_asphalt_road) image from polyhaven (2k, .exr). It contains a very bright spot around pixel coordinate [1229,253] when I convert it using `.\ktx.exe create --format R16G16B16A16_SFLOAT C:\path\to\rural_asphalt_road_2k.exr C:\path\to\envMap.ktx` the pixels around that spot become INF

**Comment by jjiangweilan** [comment]
I think it's because I am converting it to half precision and the pixels go out of range. I will close this.

**Comment by MarkCallow** [comment]
> I think it's because I am converting it to half precision and the pixels go out of range.

I think so too. If it turns out not to be the case, let me know and I'll reopen this.
