### ISSUE TITLE
Can you make an artifact for a release that does not include the gigantic `other_lib` directory?

### ISSUE THREAD

**Issue by GasimGasimzada** [KhronosGroup/KTX-Software#763]
I am downloading source code of KTX from the public release to be able to build the loader and write in my own project. Downloading the source code of KTX is 250mb. Can we have an artifact in KTX that does not bundle the `other_lib` directory and provides only the source code (the file size gets reduced to 25mb due to KTX files in tests but it is at least downloadable in CI environments)?

**Comment by MarkCallow** [comment]
The linked PR removes `other_lib` from the repo and will close this issue. `tests/testimages` will remain but will be greatly reduced when the legacy tools and their tests are removed in the release after next. A few images will remain that are used by {es3,gl3,vk}loadtests.

**Comment by GasimGasimzada** [comment]
Thank you!

**Comment by MarkCallow** [comment]
I prefer to let this be closed when the PR is merged. Re-opening.
