### ISSUE TITLE
UWP x64 build fails due to char/wchar comparison

### ISSUE THREAD

**Issue by Pospelove** [KhronosGroup/KTX-Software#764]
https://github.com/KhronosGroup/KTX-Software/blob/0feeda6d2bac4d5d42e7d502ce4953bee664681b/utils/argparser.cpp#L76

Discovered here: https://github.com/microsoft/vcpkg/issues/33687

**Comment by MarkCallow** [comment]
I wonder why our CI doesn't complain. It builds with a high warning level specified and with warnings as errors using both clang and msvc.

**Comment by Pospelove** [comment]
> I wonder why our CI doesn't complain. It builds with a high warning level specified and with warnings as errors using both clang and msvc.

I guess it's not building a UWP build, just a regular msvc build. But can't tell for sure

**Comment by Pospelove** [comment]
my fix on vcpkg side https://github.com/microsoft/vcpkg/pull/33723
