### ISSUE TITLE
Documentation double dashes (--) turn into n-dash (–)

### ISSUE THREAD

**Issue by nighthawk469** [KhronosGroup/KTX-Software#766]
In this doc, toktx options like `--cubemap` are incorrectly formatted like `–cubemap`
https://github.khronos.org/KTX-Software/ktxtools/toktx.html

Source
https://github.com/KhronosGroup/KTX-Software/blob/main/tools/toktx/toktx.cc

I think this could be worked around using

> \\--
> This command writes two dashes (--) to the output. This allows writing two consecutive dashes to the output instead of one n-dash character (–).
https://www.doxygen.nl/manual/commands.html

Related
https://github.com/fish-shell/fish-shell/issues/1557

**Comment by nighthawk469** [comment]
I'm not sure if the doxygen docs have been regenerated yet, but I'm not seeing a change. It's possible the fix I suggested is not working.

https://github.khronos.org/KTX-Software/ktxtools/toktx.html

**Comment by MarkCallow** [comment]
The docs are only generated and published when a release is tagged and built. I have verified the fix in my local work area. I have a couple of other fixes I want to make before spinning a release.
