### ISSUE TITLE
Loading GLFuncs

### ISSUE THREAD

**Issue by addopower** [KhronosGroup/KTX-Software#768]
In the file gl_funcs.c the define of GL_FUNCTION(type, func, required) returns a bool and not a ktx_error_code_e.
So as of now the function ktxLoadOpenGLLibrary returns a success even in case of fail and the functions using it suppose everything is ok when it's not and they crash.

**Comment by MarkCallow** [comment]
Wow! This issue has been around a long time without anyone encountering it. Finding the functions must generally be reliable. What are the circumstances in which you encountered it?

Thanks for the report.
