### ISSUE TITLE
`toktx` `t2` option always on

### ISSUE THREAD

**Issue by DerRM** [KhronosGroup/KTX-Software#769]
When trying to create a KTX file with `toktx`, it always creates a KTX2 file, even when the `t2` option is not set.

Tested with:
4.2.1
4.3.0-alpha3

OS:
Windows 10 64bit

**Comment by DerRM** [comment]
Sorry, I saw that `--encode` also implies `--t2`. Very confusing as we need ASTC with KTX1 files...

**Comment by DerRM** [comment]
We have some legacy KTX files which also support ASTC and ETC1/2. We now would need to migrate to KTX2. No problem really, but I thought there would be a wrapper for ASTC files as our artists also need mipmaps with compressed formats.

**Comment by MarkCallow** [comment]
Not sure what you mean by "a wrapper for ASTC files". KTX v1 fully supports them. It is only `toktx` that does not support creating them which is because ASTC encoding support was added after v2 was available and, as I said, we couldn't see a good reason to do the additional work for creating v1 files as well. Note that the new unified `ktx` tools in 4.3 only support v2.

**Comment by DerRM** [comment]
As there is no standard way to create a mipmap chain with i.e. `astc-encoder` we need a way to 'package' prebaked mipmaps inside a container format like KTX. I don't know any tool who does that.
The tools here can generate mipmaps on the fly but unfortunately don't support KTX1 for ASTC. Maybe there are plugins for image authoring tools like PS, which do support something like that but I really don't know.

**Comment by MarkCallow** [comment]
When you say `astc_encoder` are you referring to ARM's encoder? `toktx` can generate mipmaps, `--genmipmap`, before ASTC encoding but the result will be KTX v2 files. It can also accept pre-baked mipmaps to which it will apply the ASTC encoder. The new `ktx create` tool can do the same things but with a different command line.

`toktx` has been deprecated and will be replaced by the new v2 only tools. I recommend you change your loader/pipeline to use KTX v2 so you can take advantage of these tools. There are loaders for OpenGL and Vulkan in libktx.  They support v1 and v2. I have open issues seeking volunteers to provide PRs with loaders for DX12 and Metal.
