### ISSUE TITLE
CLI tool error: my-file.ktx is not a KTX or KTX2 file

### ISSUE THREAD

**Issue by harelfar2** [KhronosGroup/KTX-Software#772]
Hi. 
I have some ktx files that were created in my IPhone. 
[example attached here](https://github.com/KhronosGroup/KTX-Software/files/12656874/ktx-file.zip)
I tried to extract them in the CLI tool with ubuntu, but got this error: `.ktx is not a KTX or KTX2 file.`
Can you help me identify what wrong with this file, and how can I transcode it? 
(I zipped this file, since I cannot upload this type of file)

Thanks a lot.

**Comment by MarkCallow** [comment]
The tool is correct. It is not a KTX file.It's first 4 bytes are "AAPL".
