### ISSUE TITLE
Incorrect option for ktx create docs

### ISSUE THREAD

**Issue by matthew-rister** [KhronosGroup/KTX-Software#790]
The docs for `ktx create` indicate that `--zcmp` is highly encouraged when using `--encode uastc`, however, this option does not exist. Did you mean `--zstd` or `--zlib`?

**Comment by MarkCallow** [comment]
`--zstd`. Sorry for the documentation error. @aqnuep please fix.

**Comment by aqnuep** [comment]
I cannot see any reference to `zcmp` in the new `ktx` tool code or documentation. Only the old `ktxsc` and `toktx` tools refer to it.

Where is this documentation that you talk about? I can only see the new `ktx` tool doc saying:

````
            You are strongly encouraged to also specify @b --zstd to
            losslessly compress the UASTC data.
````

**Comment by matthew-rister** [comment]
There is still a reference to `--zcmp` in the description for `--uastc quality <level>` option here: https://github.khronos.org/KTX-Software/ktxtools/ktx_create.html. I also encountered it after running the Windows installer and running `ktx --help`.

**Comment by MarkCallow** [comment]
This may have been fixed since the alpha3 release.

**Comment by MarkCallow** [comment]
This has indeed already been fixed.

```
git diff v4.3.0-alpha3 tools/ktx/encode_utils.h
...
-            You are strongly encouraged to also specify @b --zcmp to
+            You are strongly encouraged to also specify @b --zstd to
...
```

The fix will appear in the next release.
