### ISSUE TITLE
Can not find __std_stream header

### ISSUE THREAD

**Issue by FuXiii** [KhronosGroup/KTX-Software#791]
Please check [Can not find __std_stream](https://github.com/mstorsjo/llvm-mingw/issues/377)

**Comment by MarkCallow** [comment]
@aqnuep this is due to a non-portable include in the version of {fmt} that we are using.  See https://github.com/fmtlib/fmt/issues/3654. Please update the included version of {fmt}. While doing it, also consider #786.
