### ISSUE TITLE
ktxTexture_GetImageSize doesn't handle 3D textures

### ISSUE THREAD

**Issue by AlexRouSg** [KhronosGroup/KTX-Software#792]
I am trying to create a 3D `ktxTexture2` from image data in memory however it fails at `ktxTexture_SetImageFromMemory` with `KTX_INVALID_OPERATION.`

Debugging the code it appears as if `ktxTexture_GetImageSize` doesn't handle 3D texture sizes at all which then triggers this failure condition in `ktxTexture2_setImageFromStream`
```
    if (srcSize != imageByteLength)
        return KTX_INVALID_OPERATION;
```

This is on the main branch just pulled at the time of this issue creation.

Unless I am meant to set the individual 2D slices of the 3D texture then the documentation is not clear that is what I have to do.

**Comment by MarkCallow** [comment]
The documentation for `ktxTexture[12]_GetImageSize says

```
 * For arrays, this is the size of a layer, for cubemaps, the size of a face
 * and for 3D textures, the size of a depth slice.
 ```

The documentation for the `faceSlice` parameter of `ktxTexture2_setImageFromStream` says

```
 * @param[in] faceSlice cube map face or depth slice of the image to set.
```

which to me clearly indicates you have to upload a slice at a time. Happy to make clarifications, if you'd like to propose something concrete.

I'd also be happy to better support creation of 3d textures. Are you working a file format that supports 3d image data? Please propose an API that would helpful to you. Probably will need new SetImage functions that take all slices at once and would not be usable with any other type of texture.

Are you generating mip levels for your 3d textures? The generator currently used by the KTX tools only supports 2d mip level generation. An extra dimension of filtering is needed for 3d.

**Comment by AlexRouSg** [comment]
> which to me clearly indicates you have to upload a slice at a time. Happy to make clarifications, if you'd like to propose something concrete.

That's kinda surprising to me that you have to do it that way, cause I've edited the `ktxTexture_GetImageSize` function to include depth and it works and creates a valid ktx2 file when given an uncompressed R8G8B8A8 image. But I don't know what is the correct size calculation to handle every format.

> Are you generating mip levels for your 3d textures?

Not currently but maybe, still investigating what to do atm.

**Comment by MarkCallow** [comment]
> That's kinda surprising to me that you have to do it that way, 

It works as documented...

> cause I've edited the ktxTexture_GetImageSize function to include depth and it works

Do not do this. It will break the level size and level offset calculations as the 2D image size (in bytes) will now be multiplied by the square of the number of depth slices. Since you only have a base mip level at present you won't notice the breakage but broken it is.

The proper fix is to add new `ktxTexture_Set3dImageFrom*` functions which use the level size instead of 2d image size as a sanity check. A modified ktxTexture2_setImageFromStream` should underlie both old and new functions. A flag parameter can be used to tell it which sanity check to use.

**Comment by MarkCallow** [comment]
> The proper fix is to add new ktxTexture_Set3dImageFrom* functions 

On reflection, this is overkill. A simple fix to the sanity check will work. Compare the provided size with the result of `ktxTexture_GetImageSize()` for non-3d textures and for 3d textures when the faceSlice parameter != 0. For 3d textures with faceSlice == 0, allow size equal to either `ktxTexture_GetImagesize()` or `ktxTexture_calcLevelSize()`.  The level size equals the sum of the 2d slice sizes. With that fix you'll be able to upload your 3d texture.

Do you have a file format you are working with?

**Comment by AlexRouSg** [comment]
> A simple fix to the sanity check will work

yes that does look like better UX, maybe instead of 0, use `-1` for less chance of user error?

> Do you have a file format you are working with?

I have a private file format I am working on but it's in too early a state to know what more I need from libktx

**Comment by MarkCallow** [comment]
> > A simple fix to the sanity check will work
> 
> yes that does look like better UX, maybe instead of 0, use `-1` for less chance of user error?
> 

You mean a faceSlice value of -1 to modify the sanity check, right? Yes that sounds good. If you create a PR to fix  `ktxTexture2_setImageFromStream` I'll be happy to accept it.

> > Do you have a file format you are working with?
> 
> I have a private file format I am working on but it's in too early a state to know what more I need from libktx

When you do know, please let me know. I'll be happy to provide better support for 3d textures.
