### ISSUE TITLE
unclear how to free memory allocated in functions saying "caller is responsible for freeing it"

### ISSUE THREAD

**Issue by AlexRouSg** [KhronosGroup/KTX-Software#793]
So I noticed there are some functions that say "caller is responsible for freeing it" however it is not clear how is one supposed to free said memory, assuming it means literally calling `free()`, how would that work when libktx is built as a dynamic library? 

Don't memory allocated within a dynamic library have to also be freed from within said dynamic library due to multiple instances of the C runtime and stuff?

**Comment by MarkCallow** [comment]
> Don't memory allocated within a dynamic library have to also be freed from within said dynamic library due to multiple instances of the C runtime and stuff?

No. Shared libraries share code not data. Each process has its own global, heap and stack data. Call `free()` to free returned data. How would you like to see the documentation clarified?
