### ISSUE TITLE
CLI crashes when using `--assign-oetf srgb|linear`

### ISSUE THREAD

**Issue by Calinou** [KhronosGroup/KTX-Software#795]
**OS:** Fedora 38 x86_64
**KTX Software version:** 4.3.0-alpha3 (does not occur in 4.2.1)

The CLI crashes when using `--assign-oetf srgb` or `--assign-oetf linear` (with the appropriate format chosen):

```
./ktx create --assign-oetf srgb --format R8G8B8A8_SRGB input.png output.ktx
ktx create warning: No color primaries in PNG input file "input.png", defaulting to BT.709.
[1]    51444 segmentation fault (core dumped)  ./ktx create --assign-oetf srgb --format R8G8B8A8_SRGB
```

If I don't specify this option, I get the following error instead:

```
ktx create warning: No color primaries in PNG input file "input.png", defaulting to BT.709.
ktx create fatal: Input file "input.png" contains unsupported ICC profile "icc". Use --assign-oetf to specify adifferent one.
```

Input image:

![godot_icon_ktx](https://github.com/KhronosGroup/KTX-Software/assets/180032/1c8e8c79-f386-411f-81ad-3ecc5ddac4da)

**Comment by aqnuep** [comment]
This seems to work with the latest code in `main`. Could have been another corner case that I've fixed related to color-space handling a couple of months ago.

**Comment by arpu** [comment]
any plans for new release soon?

**Comment by MarkCallow** [comment]
> any plans for new release soon?

As soon as I fix issues 774, 791 and 796.

This issue is fixed in `main`. Closing.
