### ISSUE TITLE
Non-square EXR encodes with incorrect texture height

### ISSUE THREAD

**Issue by krispya** [KhronosGroup/KTX-Software#798]
Using 4.3.0-alpha3, I am attempting to encode an EXR file with 4096x2048 dimensions. The result looks like this:

![image](https://github.com/KhronosGroup/KTX-Software/assets/7064954/26c7fe01-9a1e-4889-babd-dccf508cadbd)

However, if I resize the same EXR to be square (2048x2048) then it encodes just fine.

![image](https://github.com/KhronosGroup/KTX-Software/assets/7064954/b420c531-ebac-450a-b220-1b8a7254c384)

I would expect the encoded texture to match with the power of 2 dimensions just fine.

This is my command line:
```
ktx create --format R16G16B16A16_SFLOAT sky_linekotsi_23_2048.exr sky_linekotsi_23tt.ktx2
```

Here are the files for reference: https://www.dropbox.com/sh/u2htkdglhjopogy/AAAzXXedlJCm-THj1EWgYRBoa?dl=0

**Comment by MarkCallow** [comment]
Please add the non-square EXR to the dropbox. It has only a non-square Radiance file and the square EXR. We need to see the input you used.

**Comment by krispya** [comment]
My mistake, I dragged the wrong file over. It should be there as `sky_linekotsi_23.exr`.

**Comment by MarkCallow** [comment]
The result looks fine to me.

<img width="1392" alt="Screenshot 2023-11-10 at 12 43 46" src="https://github.com/KhronosGroup/KTX-Software/assets/2244683/da813a12-1c54-47c5-9ab7-572ccca56f96">

I am using a slightly later version of `ktx create` but the change logs between 4.3.0-alpha3 and what I am using do not reflect any change that might have fixed this problem except perhaps this one:

```
commit 682f456de1402c2256cdc2b2fe21c0e8c54b4915
Author: Cs<C3><A1>sz<C3><A1>r M<C3><A1>ty<C3><A1>s <VaderY@users.noreply.github.com>
Date:   Thu Jul 13 13:38:20 2023 +0200

    Fix incorrect index calculations in image conversions (#735)
    
    Fixes #733. Fixes #736.
```

@aqnuep please comment.

**Comment by krispya** [comment]
Thanks for checking on this so fast. In a sense this is a big relief and also not. Now I need to figure out why my environment is making incorrect textures. 😆

**Comment by aqnuep** [comment]
There was at some point an issue, where the width and height parameters within the EXR path in the image input library were accidentally flipped somewhere, which was fixed a couple of months ago. I expect this was caused by that.

**Comment by krispya** [comment]
I can confirm this is fixed with a build from main. I'm looking forward to a new alpha being cut!
