### ISSUE TITLE
Create should verify ASTC options and the format provided

### ISSUE THREAD

**Issue by abbaswasim** [KhronosGroup/KTX-Software#808]
If an ASTC encode is intended by providing any of the astc encode options to "ktx create" the options should be verified for compatibility along side the VK_FORMAT provided.

**Comment by MarkCallow** [comment]
Currently, per the documentation, astc encoder arguments are ignored if the `--format` argument is not an ASTC format. It seems like users will easily be caught out by this. I agree with @abbaswasim that an error should be flagged in this case. @lexaknyazev, @aqnuep what do you think?

**Comment by lexaknyazev** [comment]
Makes sense to reject invalid commands.

**Comment by wasimabbas-arm** [comment]
I tried `--format R8G8B8A8_SRGB --astc-quality fastest --astc-perceptual` and apparently these are incompatible but not reported.
