### ISSUE TITLE
Conversion to ktx2 using toktx of a jpg image is resulting into a black ktx2 texture

### ISSUE THREAD

**Issue by mahfouzhseineweev** [KhronosGroup/KTX-Software#818]
I have a jpg texture that I am trying to convert using the KTX-Software into a ktx2 file but when I do so using toktx, the result I am getting is a full black texture.

Here are the details I have:

* toktx v4.0
* Image size: 8.1 MB
* Image Dimensions: 13500 × 6750
* Image color space: RGB
* Image color profile: sRGB
* Command used: `toktx --2d --genmipmap --target_type RGBA --t2 --scale 1.0 --encode etc1s --clevel 0 --qlevel 255 --lower_left_maps_to_s0t0 nightTexture.ktx2 nightTexture.jpg`
   - Tried with RGB target type and got the same problem

* Image to convert:

![earthNight](https://github.com/KhronosGroup/KTX-Software/assets/101403093/79ebd64a-47d3-426e-9b09-5c3bb68482b5)

* I am testing the ktx2 result here: https://sandbox.babylonjs.com/

* My intension is to use the ktx2 file on three js using the KTX2Loader 

Note that I have used the exact same command options on other textures and they were created with no problem.

Please help me understand and solve the problem I am facing, thank you.

**Comment by MarkCallow** [comment]
That exact command is working for me in the 4.3.0 beta I am currently preparing and will soon release. Because of the `--target_type` it might not work in v4.3.0-alpha3 or v4.2.1. v4.0 is now very old. Please try a more recent version of toktx. 

Note that the `--target_type` serves no purpose here. The ETC1S encoder will strip an all-1 alpha channel to avoid doubling the size of the texture. Therefore asking toktx to add an alpha channel just wastes cpu cycles.

Here is an image showing all the mip levels and the lights are clearly visible.

<img width="1392" alt="Screenshot 2023-12-15 at 17 08 38" src="https://github.com/KhronosGroup/KTX-Software/assets/2244683/3a7cb7bb-6c63-4304-bfb4-0427ecd4f43e">

**Comment by mahfouzhseineweev** [comment]
@MarkCallow I tried without the --target_type but it didn't work. So it seems like the v4.3.0 beta has the fix for it.
I currently have the v4.3.0-alpha3 installed.

When is the v4.3.0 beta expected to be release ?

**Comment by MarkCallow** [comment]
> When is the v4.3.0 beta expected to be release ?

Within a few days. I can't give a precise time frame because I am dependent on third parties for some things.

**Comment by MarkCallow** [comment]
4.3.0-beta1 has been released. I can't reproduce this problem in it. If it still happens for you, please reopen.

**Comment by mahfouzhseineweev** [comment]
I still have the same problem, installed the 4.3.0-beta1 version from [here](https://github.com/KhronosGroup/KTX-Software/tree/v4.3.0-beta1)

I am suspecting this to be a versioning problem somewhere, I am running the software on the following specifications:

* macos Ventura Version 13.0
* cmake version 3.28.1
* Xcode version 14.3

@MarkCallow Please let me know if there are any additional details that I have to share with you so I can help to reproduce the problem

**Comment by MarkCallow** [comment]
Please provide the KTX v2 file you have created.

**Comment by mahfouzhseineweev** [comment]
@MarkCallow Here is the last one I created, if possible please to send me the one you created that has no problem

[nightTexture2.ktx2.zip](https://github.com/KhronosGroup/KTX-Software/files/13872142/nightTexture2.ktx2.zip)

**Comment by MarkCallow** [comment]
The texture is fine.

<img width="1392" alt="Screenshot 2024-01-11 at 18 36 50" src="https://github.com/KhronosGroup/KTX-Software/assets/2244683/af610bdd-e465-419b-aa5c-c198438d5d11">

There mayt be an issue with your application. This is an ETC1S/BasisLZ texture so possible you are not transcoding it or are transcoding it to a format not supported on your hardware. It is is not one of these then the texture loaded into WebGL may be incomplete. Look at the spec. for all the reasons a texture can be incomplete which includes, in some cases, non power-of-two textures and exceeding the maximum texture size supported by the implementation. This texture is 13,500 x 6,750 pixels.
