### ISSUE TITLE
compile fail linux

### ISSUE THREAD

**Issue by sj-m** [KhronosGroup/KTX-Software#820]
command :  cmake . -B build

assimp installed  on /usr/bin/assimp

errorMsg :
CMake Error at cmake/modules/Findassimp.cmake:84 (message):
  Could not find asset importer library
Call Stack (most recent call first):
  tests/loadtests/CMakeLists.txt:12 (find_package)

**Comment by MarkCallow** [comment]
I have no idea what /usr/bin/assimp is. You need to install assimp and assimp-dev from your package manager. E.g,

```
sudo apt-get install libassimp5 libassimp-dev
```

This will install libassimp.so.5 and cmake/assimp-5* in the library directory for your architecture and `/usr/include/assimp`. assimp is a library not a command. The build should then work.  Our CI builds successfully use Ubuntu 22.04.

**Comment by MarkCallow** [comment]
Please reopen if you still have an issue after installing libassimp and libassimp-dev.
