### ISSUE TITLE
After converting the image to ktx format using "ktx create" I get a texture that is not similar to the input image.

### ISSUE THREAD

**Issue by DmitryPor** [KhronosGroup/KTX-Software#821]
After converting the image to ktx format using "ktx create" I get a texture that is not similar to the input image.
I tried different types of compression and other settings, nothing helps.
cli: ktx create --format R8G8B8_UNORM --encode basis-lz plate_g.jpg plate_g.ktx2

image:
![plate_g](https://github.com/KhronosGroup/KTX-Software/assets/129183110/4280f778-dc77-4b3a-974b-8fbcfa8ad356)

result:
![plate_g_ktx2](https://github.com/KhronosGroup/KTX-Software/assets/129183110/433a85b7-928a-4225-b9f9-6cda69313d71)

**Comment by MarkCallow** [comment]
The fix was squash-merged into 4.3.0-beta1.
