### ISSUE TITLE
[OS X] There are no include files.

### ISSUE THREAD

**Issue by Raffaello** [KhronosGroup/KTX-Software#838]
I installed the package x86_64 darwin on a OS X 13

A project using cmake find the Ktx library, but when try compiling the source is reporting that can't find `ktx.h`.

I wasn't able to find any include files on the system at all.

I fixed it doing: copy manually the ktx.h and KHR include directory into the `/usr/local/include` (i think, sorry i don't  have 
access directly to a MacOS so can't really properly looking in to it).

I am surprised of this inconvenience as from the CMakeLists.txt file should have those include files.

Is this a issue in the CMakeLists.txt file configuration for `APPLE` or something not ok with my system?

**Comment by MarkCallow** [comment]
By default only the tools and library are installed. You have to click the _Customize_ button on the pkg install dialog then check the _Development_ box to install the include files. There is a note at the bottom of the Read Me (second) pane of the dialog saying you need to do this if developing applications. 

It seems like it is an error that the CMake file was installed without _Development_ being checked. The config for your project should have failed saying it couldn't find KTX. Please confirm if the find step was indeed successful or not so I won't waste time investigating a possible non-problem.

**Comment by Raffaello** [comment]
the find step was succesful (`findpackage`). the cmake file was present as i was able to literally `find` it, but after the cmake generation step, the cmake build step was failing due to `cannot find #include <ktx.h>`. hence here this ticket.

ok thanks, for that i did check on that dialog box.

**Comment by MarkCallow** [comment]
I will fix it so that the CMake files are bundled in the Development component with the header files.
