### ISSUE TITLE
Preceding `ktx` command name with option leads to error

### ISSUE THREAD

**Issue by MarkCallow** [KhronosGroup/KTX-Software#867]
The command

```
ktx --testrun extract --all --raw <input> <output>
```

produces the error

```
ktx: Unrecognized command: "extract"
```

There should not be an error in this case. Should one be unavoidable it should definitely not be saying that "extract" is an unrecognized command.

**Comment by aqnuep** [comment]
This should be an error. The subcommand name must always be the first parameter, just like in case of git (barring command-independent parameters, which the ktx CLI tool does not have).

It is weird that for "--testrun" it says the unrecognized command is "extract", while for other "--parameter" values I get the proper error of unrecognized command "--parameter".

It must be something special with the way "--testrun" is handled. I'll try to take a look at it if I'll have time.
