### ISSUE TITLE
Skipping mipmaps when loading from disk

### ISSUE THREAD

**Issue by Flone-dnb** [KhronosGroup/KTX-Software#901]
Hello, is there a way to skip some mips when loading a texture from disk? Consider an example where I want to load a texture that has 3 mipmaps with sizes:
- mip0 - 1024
- mip1 - 512
- mip2 - 256

but I only want to load 2 of them (skip the largest mipmap with size 1024 and don't load it into the memory) so that my final (loaded) texture will only have 2 mips with sizes 512 and 256.

I'm currently using `ktxTexture_CreateFromNamedFile` and `ktxTexture_VkUploadEx_WithSuballocator` to load textures.

Thanks.

**Comment by MarkCallow** [comment]
`VkUpload` does not provide any control over loading only some of your mipmaps. I will be happy to accept a PR to add this functionality should your need motivate you to add the functionality.

**Comment by Flone-dnb** [comment]
So after spending a few hours trying to implement this feature I eventually gave up on it and just copied the loaded texture to a new one but skipped required mips. It's not a good solution but it satisfies me for now. Thanks for the info anyway.

Feel free to close this issue.
