### ISSUE TITLE
Binaries publishing

### ISSUE THREAD

**Issue by lexaknyazev** [KhronosGroup/KTX-Software#91]
Tagged releases should have pre-built binaries (an archive with libraries, headers, and command-line tools) automatically published for all platforms. Executable code should have Khronos signature (as it becomes available).

**Comment by MarkCallow** [comment]
Where should these binaries be published? It needs to be accessible from the CI bots so they can update the binaries when a release is tagged.

**Comment by lexaknyazev** [comment]
There's a dedicated GitHub page for releases:
https://github.com/KhronosGroup/KTX-Software/releases

Travis can upload build artifacts automatically:
https://docs.travis-ci.com/user/deployment/releases/

**Comment by MarkCallow** [comment]
Binaries are now available. Everything mentioned is done, except signing the Windows installer for which we are awaiting a certificate.
