### ISSUE TITLE
Enabling Automatic Mipmap Generation Causes Validation Error

### ISSUE THREAD

**Issue by lashahub** [KhronosGroup/KTX-Software#912]
#### Description
I am encountering an issue when enabling automatic mipmap generation for KTX2 textures. When I set `createInfo.generateMipmaps = KTX_TRUE`, I receive a validation error while using the KTX 2.0 validator.

#### Code Example
```cpp
#include <ktx.h>
#include "../texture.h"
#include "../vkformat_enum.h"

void writeKTX2(const Texture &rawTexture, CompressionMode mode, bool isNormal) {
    ktxTexture2 *texture;
    ktxTextureCreateInfo createInfo = {};
    createInfo.vkFormat = VK_FORMAT_R8G8B8A8_UNORM;
    createInfo.baseWidth = rawTexture.imageData.width;
    createInfo.baseHeight = rawTexture.imageData.height;
    createInfo.baseDepth = 1;
    createInfo.numDimensions = 2;
    createInfo.numLevels = 1;
    createInfo.numLayers = 1;
    createInfo.numFaces = 1;
    createInfo.isArray = KTX_FALSE;
    createInfo.generateMipmaps = KTX_TRUE; // Enabling mipmaps

    if (ktxTexture2_Create(&createInfo, KTX_TEXTURE_CREATE_ALLOC_STORAGE, &texture) != KTX_SUCCESS) return;

    if (ktxTexture_SetImageFromMemory(ktxTexture(texture), 0, 0, 0,
                                      reinterpret_cast<const ktx_uint8_t *>(rawTexture.imageData.pixels.data()),
                                      sizeof(Pixel) * rawTexture.imageData.pixels.size()) !=
        KTX_SUCCESS) {
        ktxTexture_Destroy(ktxTexture(texture));
        throw runtime_error("Failed to set image from memory");
    }

    ktxBasisParams params;
    memset(&params, 0, sizeof(params));
    params.structSize = sizeof(params);
    params.uastc = mode == UASTC;
    params.verbose = KTX_FALSE;
    params.noSSE = KTX_FALSE;
    params.threadCount = 1;

    // ETC1S parameters
    params.compressionLevel = 4;
    params.qualityLevel = 255;
    params.normalMap = isNormal ? KTX_TRUE : KTX_FALSE;

    // UASTC parameters
    params.uastcRDO = KTX_TRUE;
    params.uastcRDOQualityScalar = 0.8f;
    params.uastcRDODictSize = 4096;

    if (ktxTexture2_CompressBasisEx(texture, &params) != KTX_SUCCESS) {
        ktxTexture_Destroy(ktxTexture(texture));
        throw runtime_error("Failed to compress ktx2 file: " + rawTexture.texturePath.string());
    }
    if (mode == UASTC && ktxTexture2_DeflateZstd(texture, 10) != KTX_SUCCESS) {
        ktxTexture_Destroy(ktxTexture(texture));
        throw runtime_error("Failed to deflate ktx2 file: " + rawTexture.texturePath.string());
    }
    if (ktxTexture_WriteToNamedFile(ktxTexture(texture), rawTexture.texturePath.c_str()) != KTX_SUCCESS) {
        ktxTexture_Destroy(ktxTexture(texture));
        throw runtime_error("Failed to write ktx2 file: " + rawTexture.texturePath.string());
    }
    ktxTexture_Destroy(ktxTexture(texture));
}
```

#### Error Message
```
error-3017: Invalid levelCount. levelCount cannot be 0 for block-compressed formats. levelCount is 0 but for block-compressed KHR_DF_MODEL_UASTC it must not be 0.
warning-5004: Non-conformant texture file accepted by libktx. KTX 2.0 file does not conform to the specification but it is currently accepted by libktx.
```

#### Steps to Reproduce
1. Set `createInfo.generateMipmaps = KTX_TRUE` in the provided code.
2. Run the KTX 2.0 validator on the generated file.

#### Expected Behavior
Automatic mipmap generation should work without causing validation errors, especially for block-compressed formats like UASTC.

#### Actual Behavior
The validator reports an invalid `levelCount` when mipmap generation is enabled.

#### Additional Information
Without mipmaps, the code works correctly, but this leads to increased aliasing at a distance, which I am trying to avoid by using mipmaps. 

#### Environment
- **Operating system:** Debian x86-64
- **Compiler:** GCC v12
- **C++ Standard:** C++20
- **KTX-Software version:** v4.3.2~6
- **Library version:** ktx/4.0.0 installed from Conan (libktx)

Please let me know if further information is needed or if there are any known workarounds for this issue.

**Comment by MarkCallow** [comment]
`createInfo.generateMipmaps` sets up the texture to request the mipmaps to be generated by the client application at runtime. This is indicated in the created `ktxTexture2` object and in a file by setting levelCount == 0. However as generating mipmaps for block compressed textures is not widely supported in hardware the specification says this is not allowed for block-compressed textures. This includes the universal formats as, at file creation, we cannot know to what format they will be transcoded.

The only issue I see here is that `ktxTexture2_CompressBasisEx` does not return `KTX_INVALID_OPERATION` when `generateMipmaps` is set in the input `ktxTexture2`. We should probably also rename `generateMipmaps` to `runtimeMipmap` to reduce confusion.

Do not set `generateMipmaps`. Instead create your own mip levels before compression, passing each to the `ktxTexture2` object with `ktxTexture_SetImageFromMemory`.
