### ISSUE TITLE
ktxTexture_SetImageFromMemory should document pointer lifetime guarantees

### ISSUE THREAD

**Issue by matthew-rister** [KhronosGroup/KTX-Software#914]
`ktxTexture_SetImageFromMemory` (and friends) expect a `const ktx_uint8_t*` to the image source in memory. It's unclear if this takes over ownership of the pointer or if it creates a copy of the underlying image memory. Upon further investigation, it appears it [creates a copy](https://github.com/KhronosGroup/KTX-Software/blob/5fc739c8fc577946cf91509509ac189e81143d2a/lib/writer2.c#L232) of the image memory. 

To better help users avoid memory leaks (by e.g. assuming a memory ownership transfer), corresponding KTX APIs should be updates to include a note about pointer lifetime assumptions.

**Comment by MarkCallow** [comment]
Please propose a PR.

**Comment by matthew-rister** [comment]
@MarkCallow I have submitted a brief [pull request](https://github.com/KhronosGroup/KTX-Software/pull/917) with proposed documentation updates.
