### ISSUE TITLE
ktxTexture2_GetImageOffset: identifier not found

### ISSUE THREAD

**Issue by UX3D-haertl** [KhronosGroup/KTX-Software#934]
I'm getting this build error, while trying to use ktxTexture2_GetImageOffset (even though my IDE can find the function in the source code).

I'm now using 
`ktxTexture_GetImageOffset(ktxTexture(texture), 0, 0, 0, &offset);`
instead.

Other texture2 functions such as `ktxTexture2_Destroy` can be used without problems.

**Comment by MarkCallow** [comment]
It is not exposed in ktx.h, and therefore on Windows is not added to dll exports (when building libktx) and imports (when compiling apps.)

I'll happily accept a PR to add it to ktx.h.
