### ISSUE TITLE
android lib build failed under macos

### ISSUE THREAD

**Issue by savvytang** [KhronosGroup/KTX-Software#951]
I'm using main branch.

[ 41%] Building C object CMakeFiles/ktx.dir/lib/writer1.c.o
[ 42%] Building C object CMakeFiles/ktx.dir/lib/writer2.c.o
[ 42%] Linking CXX shared library libktx.dylib
ld: warning: ignoring file 'external/astc-encoder/Source/libastcenc-neon-static.a[23](astcenc_weight_quant_xfer_tables.cpp.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'external/astc-encoder/Source/libastcenc-neon-static.a[22](astcenc_weight_align.cpp.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'external/astc-encoder/Source/libastcenc-neon-static.a[21](astcenc_symbolic_physical.cpp.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'external/astc-encoder/Source/libastcenc-neon-static.a[20](astcenc_quantization.cpp.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'external/astc-encoder/Source/libastcenc-neon-static.a[19](astcenc_pick_best_endpoint_format.cpp.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'external/astc-encoder/Source/libastcenc-neon-static.a[18](astcenc_percentile_tables.cpp.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'external/astc-encoder/Source/libastcenc-neon-static.a[17](astcenc_partition_tables.cpp.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'external/astc-encoder/Source/libastcenc-neon-static.a[16](astcenc_mathlib_softfloat.cpp.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'external/astc-encoder/Source/libastcenc-neon-static.a[15](astcenc_mathlib.cpp.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'external/astc-encoder/Source/libastcenc-neon-static.a[14](astcenc_integer_sequence.cpp.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'external/astc-encoder/Source/libastcenc-neon-static.a[13](astcenc_image.cpp.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'external/astc-encoder/Source/libastcenc-neon-static.a[12](astcenc_ideal_endpoints_and_weights.cpp.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'external/astc-encoder/Source/libastcenc-neon-static.a[11](astcenc_find_best_partitioning.cpp.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'external/astc-encoder/Source/libastcenc-neon-static.a[10](astcenc_entry.cpp.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'external/astc-encoder/Source/libastcenc-neon-static.a[9](astcenc_diagnostic_trace.cpp.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'external/astc-encoder/Source/libastcenc-neon-static.a[8](astcenc_decompress_symbolic.cpp.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'external/astc-encoder/Source/libastcenc-neon-static.a[7](astcenc_compute_variance.cpp.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'external/astc-encoder/Source/libastcenc-neon-static.a[6](astcenc_compress_symbolic.cpp.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'external/astc-encoder/Source/libastcenc-neon-static.a[5](astcenc_color_unquantize.cpp.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'external/astc-encoder/Source/libastcenc-neon-static.a[4](astcenc_color_quantize.cpp.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'external/astc-encoder/Source/libastcenc-neon-static.a[3](astcenc_block_sizes.cpp.o)': found architecture 'arm64', required architecture 'x86_64'
ld: warning: ignoring file 'external/astc-encoder/Source/libastcenc-neon-static.a[2](astcenc_averages_and_directions.cpp.o)': found architecture 'arm64', required architecture 'x86_64'
Undefined symbols for architecture x86_64:
  "astcenc_config_init(astcenc_profile, unsigned int, unsigned int, unsigned int, float, unsigned int, astcenc_config*)", referenced from:
      _ktxTexture2_CompressAstcEx in astc_encode.cpp.o
  "astcenc_context_free(astcenc_context*)", referenced from:
      _ktxTexture2_CompressAstcEx in astc_encode.cpp.o
      _ktxTexture2_CompressAstcEx in astc_encode.cpp.o
  "astcenc_context_alloc(astcenc_config const*, unsigned int, astcenc_context**)", referenced from:
      _ktxTexture2_CompressAstcEx in astc_encode.cpp.o
  "astcenc_compress_image(astcenc_context*, astcenc_image*, astcenc_swizzle const*, unsigned char*, unsigned long, unsigned int)", referenced from:
      _ktxTexture2_CompressAstcEx in astc_encode.cpp.o
      compressionWorkloadRunner(int, int, void*) in astc_encode.cpp.o
  "astcenc_compress_reset(astcenc_context*)", referenced from:
      _ktxTexture2_CompressAstcEx in astc_encode.cpp.o
  "astcenc_get_error_string(astcenc_error)", referenced from:
      _ktxTexture2_CompressAstcEx in astc_encode.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libktx.4.3.2.dylib] Error 1
make[1]: *** [CMakeFiles/ktx.dir/all] Error 2
make: *** [all] Error 2

**Comment by MarkCallow** [comment]
Are you using top of tree main?

What is your host device and OS (what you are buliding on) and what is your target device? If you are building for an Android device then arm64 is the correct architecture. Are you building for a simulator?

I do not have Android NDK so am not in a position to reproduce the problem.

**Comment by MarkCallow** [comment]
Also in the root `CMakeLists.txt` somewhere after line 214, say at line 224, please add

```
cmake_print_variables(CPU_ARCHITECTURE)
```

run your CMake configure step and tell me what it says the CPU_ARCHITECTURE is.

**Comment by MarkCallow** [comment]
Can't progress this without the requested information.
